### ISSUE TITLE
Transitions do not work in Safari

### ISSUE THREAD

**Issue by T94T** [bertrandg/angular-split#100]
My markup looks like this:
```
<split direction="horizontal"
         gutterSize="6"
         useTransition="true"
         (dragProgress)="draggingInProgress($event)"
         (transitionEnd)="transitionEnd($event)">...
```
It seems transitions do not work either in Safari. I tried your example https://bertrandg.github.io/angular-split/#/examples/split-transitons 

I'm running your code on:
macOS: 10.13.3
Browser: Safari 11.0.3
Angular: 5.2.4
angular-split: 1.0.0-rc.3

**Comment by bertrandg** [comment]
Like for IE & Edge (#103), I've just discovered `transition: flex-basis .3s;` is not working on Safari:
https://github.com/philipwalton/flexbugs#flexbug-16

And because transitions are for estethic purpose, I don't plan to fix this, sorry.
I hope they will work on and solve it.

**Comment by T94T** [comment]
Ok, thanks for your investigations.
