### ISSUE TITLE
Support rxjs 6

### ISSUE THREAD

**Issue by alvachien** [bertrandg/angular-split#104]
Since the Angular 6 switch rxjs6, please consider upgrade this package to support rxjs 6 as well.

**Comment by aureliocalegari** [comment]
Any idea when it will support angular 6 / rxjs 6?

**Comment by aszechlicki** [comment]
I created a PR with support for rxjs6:
https://github.com/bertrandg/angular-split/pull/105
@bertrandg please have a look at it

**Comment by cipchk** [comment]
Hi @bertrandg , any update on this issue?

**Comment by camargo** [comment]
To get this working until this is updated, use: `npm install --save rxjs-compat` in your project.

**Comment by andrewinkler1** [comment]
any update on this issue

**Comment by JacobSiegle** [comment]
Needed to update my project so I made a fork of the few angular 6 fixes from aszechlicki, and some fixes of my own. I also reorganized some functions a bit to stop VSCode from giving me a giant wall of TsLint red.

Here is the npm package, use the latest version the others wont work (failed with npm) - 
https://www.npmjs.com/package/angular-split-ng6

Here is the git source commit with all changes - 
https://github.com/JacobSiegle/angular-split/commit/9a1925f89f36be9c5152d2d4e6697317a3c1dd0d

I only use the library in the most basic case so YMMV, but I would expect it to work. I'm not planing on maintaining currently so keep your issues here.

**Comment by J-Strong** [comment]
Has any progress been made on this issue, any updates at all? @bertrandg

**Comment by calebeaires** [comment]
Hi @bertrandg!

Do intend to update your plugin to work with Angular 6?

**Comment by Emeryao** [comment]
+1

**Comment by Rush** [comment]
:+1: 

Thanks @JacobSiegle

**Comment by manndave** [comment]
If anyone cares to just make the edits themselves, here's what you need.  All edits in angular-split.js

Change the 2 RxJS imports at the top to this:
```
import { Subject as Subject$1 } from 'rxjs';
import {debounceTime} from 'rxjs/operators';
```

Change line 62 to this:
`this.transitionEnd = (/** @type {?} */ (this.transitionEndInternal.asObservable())).pipe(debounceTime(20));`

Things will start working again.  **Note that this is just a quick hack until the official repo is updated**

**Comment by Rush** [comment]
@manndave `angular-split-ng6` seems to be working fine. 

Maybe there should be `angular-split-ngx`?

Of course having the root repo fixed is a superior solution.

**Comment by manndave** [comment]
@Rush - yup, just figured I'd paste the changes in case anyone (like me) wasn't able to or interested in switching to another package until this one is fixed.

**Comment by mann-david** [comment]
Because I can't stand retyping things...here's a way to automate this fix:

1. Create a file called **nodepatch.js** in the same folder as your package.json
2. Paste the code form the bottom of this comment into that file and save it.
3. Make sure you have a script in your package.json that looks like this: `"postinstall": "node nodepatch.js",`

Now the files will be patched for you every time you run yarn or npm.

```
const fs = require('fs');
const f = 'node_modules/angular-split/src/components/split.component.d.ts';
const f2 = 'node_modules/angular-split/esm5/angular-split.js';

fs.readFile(f, 'utf8', function(err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace('rxjs/Observable', 'rxjs');
  var result = result.replace("import 'rxjs/add/operator/debounceTime'", "import { debounceTime } from 'rxjs/operators'");
  fs.writeFile(f, result, 'utf8', function(err) {
    if (err) return console.log(err);
  });
});

fs.readFile(f2, 'utf8', function(err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace('rxjs/Subject', 'rxjs');
  var result = result.replace("import 'rxjs/add/operator/debounceTime'", "import { debounceTime } from 'rxjs/operators'");
  var result = result.replace('.debounceTime(20)', '.pipe(debounceTime(20))');
  fs.writeFile(f2, result, 'utf8', function(err) {
    if (err) return console.log(err);
  });
});

```

**Comment by sssalib42** [comment]
Hey there, I'm willing to help!
It's not a big task to update the code from rxjs 5 to rxjs 6!

I have done it in our project and two other github libraries so far.
Change the import statements and use pipes, is the summary. Easy, I think.

Now, what's the solid plan to upgrade the project?

Note, I'm ready to remove rxjs-compat from our project, if it wasn't for angular-aplit holding my team, and many other teams it seems like.

**Comment by sssalib42** [comment]
Can someone kindly provide an answer?!
Why aren't we on rxjs 6 until now? I'm willing to contribute. Is this a future feature, or is it not going to ever be included?

**Comment by aszechlicki** [comment]
all evidence suggests that this repo has been abandoned - author didn't answer any messages since at least April

in one of the comments above there is a link to a forked version wich has been migrated to ng6:
https://github.com/bertrandg/angular-split/issues/104#issuecomment-395592337

**Comment by destus90** [comment]
@sssalib42 I think we should search another split-library. It seems like the author has forgotten about this and do nothing.

**Comment by MTschannett** [comment]
@destus90 why do you not create a mainatained fork of this project instead of looking for another library?
Maybe they can be reunited in the future

**Comment by destus90** [comment]
@MTschannett At the moment this library works with rxjs-compat as well. Maybe in the future when it won't work we will fork it and upgrade to the newest version of Angular and rxjs.

**Comment by bertrandg** [comment]
Please check this: https://github.com/bertrandg/angular-split/issues/122
