### ISSUE TITLE
resizing on gutterClick sometimes doesn't work

### ISSUE THREAD

**Issue by rodrfons** [bertrandg/angular-split#109]
Link [demo:](https://angular-z4ahfq.stackblitz.io/)
In the demo above we have a page divided in 3 parts using angular-split.
We are using the gutterClick to resize the left split-area when clicking on the gutter.
The problem happens when the left split-area is dragged all the way to the right, passing above the right split-area to the end.
After that is done, clicking on the gutter of the left split-area will no longer resize the split-areas as expected.

**Comment by zachpappalau** [comment]
I am having the same issue in an application I am building. At the start they both have a default of 50. On "gutterClick" I set one of split area sizes to zero and the other to 100. If they click it again it brings both them back to 50. But if you move the gutter at all after the gutters size was set to 0, setting the size doesn't move the areas at all. 

    if(event.sizes[0] > 0){
      this.heightMap = 0;
      this.heightContent = 100;
    }
    else{
      this.heightMap = 50;
      this.heightContent = 50;
    }

Note: Changing the sizes outside of the gutterClick did get it out of this state. I added a toggle button which called the same method through a button click. After that it would act as expected. But if you did what was discussed above it would break again.

**Comment by chetanladdha** [comment]
Have you added toggle button on gutter itself?

**Comment by zachpappalau** [comment]
@chetanladdha: No the toggle buttons are on the header of the application.
Can you add them on the gutter itself?

![splitter-screenshot](https://user-images.githubusercontent.com/10301089/41557346-5cc65aec-730b-11e8-87e0-db261c9cebf9.png)

**Comment by bertrandg** [comment]
@rodrfons Check this stackblitz if still interesting about:
https://stackblitz.com/edit/angular-uf5h8p

You were missing catch the `dragEnd` event to update your area sizes.
But there were weird cases with `gutterClick` event in my code too, I've just published a new version `1.0.2` which solves it (the stackblitz is using it).

Reopen if still wrong for you.

@zachpappalau @chetanladdha check the stackblitz and let me know if you need more informations.
