### ISSUE TITLE
Is this component still maintained?

### ISSUE THREAD

**Issue by brian428** [bertrandg/angular-split#113]
I see the last commit was back in January for an RC release.

**Comment by Karamuto** [comment]
Same here, could need an update to angular 6 and rxjs 6

**Comment by benk79** [comment]
Same here, any news ? Or someone forked and included https://github.com/bertrandg/angular-split/pull/105 ?

**Comment by Mysame** [comment]
@bertrandg , any clarification from your end?
(I know he's still alive, but his contributions to github seem to have stopped entirely).

**Comment by leonardochaia** [comment]
Any news on this? :(
@bertrandg  maybe you could name some contributors ?

**Comment by leonardochaia** [comment]
@brian428 yeah, unfortunately I did remove it and replaced it by plain @angular/flex-layout.

There's a good example in the [FlexLayout repo](https://github.com/angular/flex-layout/tree/eda12c382c9ea2cc959ec27252b90c6f052a1fba/src/apps/demo-app/src/app/github-issues/split)

**Comment by Vx2gas** [comment]
@brian428 Any example or documentation on how to use the splitter?  Sample app anywhere?
Thanks!

**Comment by bertrandg** [comment]
Check this: https://github.com/bertrandg/angular-split/issues/122
