### ISSUE TITLE
error when using with angular 6

### ISSUE THREAD

**Issue by akhil-karat** [bertrandg/angular-split#116]
I am getting following error when running my angular 6 project using yarn start after installing angular-split@^1.0.0-rc.3. 
```
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/angular-split/src/components/split.component.d.ts(2,10): error TS2305
```
Looks like the library imports Observable using rxjs/Observable. but in my project i use rxjs 6.6.2 and Observable is directly imported from 'rxjs'. I am using yarn for installing dependencies.

**Comment by HollandRisley** [comment]
To get this working until it's updated use: npm install --save rxjs-compat in your project.

**Comment by akhil-karat** [comment]
Thanks. That works for now.

**Comment by sssalib42** [comment]
Hi guys, I'm trying to finally get rid of rxjs-compat from our project. What's the plan going forward to upgrade to using rxjs 6 syntax? Any timeline for the next release?

**Comment by bertrandg** [comment]
Please check this: https://github.com/bertrandg/angular-split/issues/122
