### ISSUE TITLE
dragStart and dragEnd - not calling functions in Angular 6

### ISSUE THREAD

**Issue by HollandRisley** [bertrandg/angular-split#117]
I can't get the startDrag and endDrag to trigger events in Angular 6.

` <split dragStart="dragStarted()" dragEnd="dragEnded()" direction="vertical">`

These functions are not triggering in my controller, though the split dragging is working.

**Comment by JinTak** [comment]
Possible solution: Put parentheses around (dragStart) and (dragEnd). You can also pass in $event parameter to access values. (dragStart)="dragStarted($event)". Hopefully that works for you. 

Cheers

**Comment by bertrandg** [comment]
Like @JinTak said, it was a syntax error.
