### ISSUE TITLE
How to move two splitters at the same time?

### ISSUE THREAD

**Issue by gutal1n** [bertrandg/angular-split#118]
I need to split the screen horizontally. And then split each part still vertically. It is necessary that when moving one of the vertical splitters, the second moves in synchronism with it. 
![123](https://user-images.githubusercontent.com/2278018/45478451-42223f80-b744-11e8-9916-d721f86ba88d.jpg)
I see that when the splitter moves, the code is executed outside the zone. I wanted to bind the size of the containers, but this did not work. The end method works correctly, but if you add a zone in the drag method everything hangs and stops moving
```
<split direction="vertical">
    <split-area size="50">
        <split (dragProgress)="drag($event)" (dragEnd)="end($event)">
          <split-area [size]="sizeLeft">
              <div>A</div>
          </split-area>
          <split-area [size]="sizeRight">
              <div>B</div>
          </split-area>
        </split>
    </split-area>
    <split-area size="50">
            <split>
              <split-area [size]="sizeLeft">
                  <div>C</div>
              </split-area>
              <split-area [size]="sizeRight">
                  <div></div>
              </split-area>
            </split>
    </split-area>
  </split>

export class AppComponent {
  sizeLeft: number = 30;
  sizeRight: number = 70;

  constructor(private _renderer: Renderer2, private zone: NgZone, private ref: ChangeDetectorRef) {}

  drag(event:any) {
      this.sizeLeft= event.sizes[0];
      this.sizeRight = event.sizes[1];
  }
  end(event:any) {
    this.zone.run(()=>{
      this.sizeLeft= event.sizes[0];
      this.sizeRight = event.sizes[1];
  }
}

**Comment by bertrandg** [comment]
Done `npm i angular-split@1.0.1`

**Comment by gutal1n** [comment]
Hi, could you give me code example please. Because everything works as before for me.
Previously, I used this "crutch" 
`dragTop(event: any) {
    let left = this.areaLeftTop.nativeElement.style.flex;
    let right = this.areaRightTop.nativeElement.style.flex;

    this.areaLeftBottom.nativeElement.style.flex = left;
    this.areaRightBottom.nativeElement.style.flex = right;
  }

  dragBottom(event: any) {
    let left = this.areaLeftBottom.nativeElement.style.flex;
    let right = this.areaRightBottom.nativeElement.style.flex;

    this.areaLeftTop.nativeElement.style.flex = left;
    this.areaRightTop.nativeElement.style.flex = right;
  }`

**Comment by bertrandg** [comment]
I added an example there:
https://bertrandg.github.io/angular-split/#/examples/sync-split

Code:
https://github.com/bertrandg/angular-split/blob/master/src/app/component/examples/sync.route.component.ts

**Comment by gutal1n** [comment]
thanks, I didn't notice
