### ISSUE TITLE
Confused about 'display: block' on visibility

### ISSUE THREAD

**Issue by cytostatic** [bertrandg/angular-split#12]
The Visibility feature uses 'display: block' to show content at the moment.
Is it possible to use 'flex' instead? 
I think, a choosable option would be the most gentle way...

**Comment by bertrandg** [comment]
Yes, I will see what could be done, I want to avoid adding another prop for that.
I will test if `display: flex;` can satisfy all needs (like all `display: block;` behavior + `flex` ones, maybe I'm wrong.. need to test),

Currently, you can add your own `div` inside `split-area`:

```
<split-area [visible]="true">
    <div style="display: flex; width: 100%; height: 100%;">
        ...
    </div>
</split-area>
```

**Comment by bertrandg** [comment]
I just figured out a better way to have a `display: flex;` applied to areas, you could simply add a css rule in the component using `<split-area>`.

Like this:
```javascript
@Component({
  selector: 'my-comp',
  styles: [`
    .area-flex {
      display: flex;
      ...
    }
  `],
  template: `
      <split direction="horizontal" [width]="500" [height]="400">
          <split-area [size]="30">...</split-area>
          <split-area class="area-flex" [size]="70">...</split-area>
      </split>`,
})
export class MyComp {}
```

Check this plunker to see it in action:
https://plnkr.co/edit/ULgAEM?p=preview
