### ISSUE TITLE
angular-split closed version and angular 7 compatibility

### ISSUE THREAD

**Issue by aiatla** [bertrandg/angular-split#121]
I'm working in a project, where i can't use a rc version, and i need to use this module to do some stuff.
I'd like to know if you plan on closing a version soon, or if you know of an alternative.
I'm willing to create a fork of this, and releasing it, but there is also the question about compatibility with angular 7. I found a fork that solves this, but is not being maintained, and was created as a temp fix. So should i create a fork on this and update it with the fix, will you update this with that fix, or is this not being maintained anymore ?

**Comment by bertrandg** [comment]
Check this: https://github.com/bertrandg/angular-split/issues/122
