### ISSUE TITLE
Library status update 📢

### ISSUE THREAD

**Issue by bertrandg** [bertrandg/angular-split#122]
Hi,
I'm the guy who coded `angular-split` and who didn't touch it since like 10 months.. 😳
Sorry about that for people who filled issues and made pull requests.

One of the reason I stopped working on was the total mess it was to manage an angular library with all packaging/bundling/import issues; the way I was coding it and testing pull requests was really bad too.
Adding to that a bit of laziness and many others things to do at home/work and you got a dead repo!

But i'm back on it, I've tested the new 'official' way to manage a library using angular-cli and that's totally awesome and painless compared to the way I was doing it before.

Currently, one of the main need is an upgrade to rxjs ^6.0.0 to make it works without rxjs-compat.

This is how I will move on first:
- first I will check pull requests, merge some of them (like #119) if I'm ok with what it does and confident it doesn't break anything and refuse others.
- set new project organisation using an angular cli configuration managing 2 projects: the library and the app demonstrating its use.
- Upgrade dependencies to `angular@^7.0.0` and `rxjs@^6.0.0`
- Commit all of this to github
- Publish an `1.0.0` version on npm

Next:
- a lot of people ask for pixel sizes (#101), and there are 3 pull requests on it, the one from mrothauer (https://github.com/bertrandg/angular-split/pull/32) is really interesting but I need to test each case I see to be sure it doesn't break anything.
- there is a mess with devicePixelRatio I need to resolve (#81 & #85) to make it works properly on desktop / mobiles / retina display.
- check all issues..

I would like to set cypress tests to back it too (I've played with it lately at work and you can simulate drag and drop easily!).

So you will get a 1.0.0 really soon! 😉

**Comment by aszechlicki** [comment]
That's a great news!
looking forward for the updated version

**Comment by beeman** [comment]
Hey @bertrandg, awesome to hear you're picking up work on this library again! 👍

**Comment by cordulegaster** [comment]
Great news. Thanks for your efforts, it's a really useful lib!

**Comment by operamint** [comment]
Thanks for that. Will be included in our project when ready!

**Comment by bertrandg** [comment]
Check #131 for what's coming.

**Comment by edjm1971** [comment]
Sorry if this is not the place to ask, but is there a version that is supported with Angular 6.x.x?
I'm running into brick walls, so if you have any tips I'd appreciate them.
Upgrading to 7.x is not an option at this time.

**Comment by edjm1971** [comment]
FYI to others, I found this branched version someone did that I can use: https://www.pika.dev/packages/angular-split-ng6
