### ISSUE TITLE
Not working with angular material

### ISSUE THREAD

**Issue by BertrandMarechal** [bertrandg/angular-split#123]
Hi Bertrand,

Thanks for the work, that looks amazing and something we really want to use.
Only issue, this does not seem to be working great with the basic set up of Angular material.
I have a very low knowledge of flexbox to try and understand why this is not working.

We have an application with the following packages 
```json
    "@angular/animations": "^7.0.2",
    "@angular/cdk": "^7.0.3",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.0.3",
```
And I am facing 2 issues when trying with  the [simplest example](https://bertrandg.github.io/angular-split/#/examples/simple-split) :
- In orientation = vertical, the gutter does not move (the properties get updated on the element, but the rendered html does not move)
- In orientation = horizontal, the gutter has a 0 height, and when manually set to 100px for instance it gets usable

Question then : any idea if we are to expect any compatibility issue with Angular Material ?

I'll try to set up an example app tomorrow morning, and link it here.

Many thanks

**Comment by bertrandg** [comment]
AFAIK it should work with Angular Material, check this example:
https://stackblitz.com/edit/angular-grbvp3

You bug is not related to material, you have to set a height to your split container.

**Comment by BertrandMarechal** [comment]
Yep, that was it.
Many thanks.
