### ISSUE TITLE
Angular Split with nested splits nearly unusable in ms Edge (deal breaker)

### ISSUE THREAD

**Issue by aureliocalegari** [bertrandg/angular-split#125]
Hello Bertrandg,

Nice to see you're back. The angular-split lib is nearly unusable in ms edge with nested tags. Even the example in your own website does not work:
Here how it looks in edge:
![image](https://user-images.githubusercontent.com/1736960/48518483-dbdda880-e8bd-11e8-86f8-df5dbb835a54.png)

And here how we would like it to look like (glorious Chrome):
![image](https://user-images.githubusercontent.com/1736960/48518564-24956180-e8be-11e8-8d95-5d8d2f0ccd9c.png)

**Comment by bertrandg** [comment]
Solved in `1.0.4`, website is up to date, you can check there:
https://bertrandg.github.io/angular-split/#/examples/nested-split

Here is what I did to solve it (except `event.preventDefault();` which should be in another commit) if you're interested about: https://github.com/bertrandg/angular-split/commit/49795155d904463fb077a664e413abfeed6917e1
