### ISSUE TITLE
Split does not work in Edge if height is 100%

### ISSUE THREAD

**Issue by robofs** [bertrandg/angular-split#126]
Split areas inside a div with height:100% do not work in Edge

Here is a sample project showing the issue
https://stackblitz.com/edit/angular-9rt13r

**Comment by bertrandg** [comment]
Not related to the lib or to a browser (your example is not working in chrome), 
If you set a height in percentage, all parent have to be setted to 100% back to the top or someone has to have an height in pixels to avoid going to the top of the DOM.

Check this stackblitz:
https://stackblitz.com/edit/angular-mnqb1y?file=src%2Fapp%2Fapp.component.html
