### ISSUE TITLE
dragEnd fired twice

### ISSUE THREAD

**Issue by jmesa-sistel** [bertrandg/angular-split#127]
I think the fix is just move `this.isDragging = false;` before 
```
        if (this.endPoint && (this.startPoint.x !== this.endPoint.x || this.startPoint.y !== this.endPoint.y)) {
            this.notify('end');
        }
```
in SplitComponent.stopDragging function

**Comment by bertrandg** [comment]
Need more context, please provide library version and stackblitz demo.

Just tested with following example on chrome/firefox/ie11/edge and it works as expected:
https://bertrandg.github.io/angular-split/#/examples/gutter-click-roll-unroll

**Comment by bertrandg** [comment]
Feel free to reopen with stackblitz demo if you reproduce it.

**Comment by jmesa-sistel** [comment]
After investigation it was my fault, I was binding a var to size and I was resetting that var after resizing the areas. Sorry.
