### ISSUE TITLE
Diagonal resizing

### ISSUE THREAD

**Issue by noririco** [bertrandg/angular-split#129]
I can see that resizing is only horizontal or vertical, what if i want each split area to interact with its nighoubors ?

**Comment by noririco** [comment]
I can resize up/down left right.
but nesting like
                      |
        a            |       b
--------------  | ----------------                 
         c            |       d

and if i move a to b ---> cd will not move
if i move a to c ---> bd will not move ALSO.

**Comment by bertrandg** [comment]
You can't move gutter horizontally and vertically at the same time but you can sync 2 split manually using `(dragProgress)` event, check this demo:
https://bertrandg.github.io/angular-split/#/examples/sync-split

**Comment by noririco** [comment]
Sorry, my bad, my issue is NOT an issue, just realized my mistake. thanks !

**Comment by bertrandg** [comment]
ok no problem! :)
