### ISSUE TITLE
Gutter hit area

### ISSUE THREAD

**Issue by vasiltabakov** [bertrandg/angular-split#130]
Is there a way for the gutter to be 1px but with larger hit area? If the hit area is just 1px it's really difficult to hit it.

I think it's probably impossible considering the current implementation, however I might be missing something.

If this were possible layouts like this would be possible too:
![image](https://user-images.githubusercontent.com/1178309/49590199-ee567980-f973-11e8-8bbf-f32384effd7f.png)
this is zoomed in photoshop mockup, the idea being having two areas of different background color and gutter with a different background, yet still easily resizeable.

**Comment by vasiltabakov** [comment]
Awesome, can't wait for the v2.0 release! Great work!

**Comment by bertrandg** [comment]
Possible with version `2.0.0` I've just released.
