### ISSUE TITLE
Library status update: Area size new features 📢

### ISSUE THREAD

**Issue by bertrandg** [bertrandg/angular-split#131]
Hi, 
I'm currently collecting all user scenarios about area size options wanted from opened issues (#4, #55, #82, #97, #101) and pull requests (#32, #36, #115).

Here is my current vision (no code yet, I'm just trying to find a solution satisfying all):
<hr>

**New `<as-split>` properties:**
* `[unit]="'percent' | 'pixel'"` ⬅️ Default to `'percent'`.
* `[gutterStep]="x"` ⬅️ Always in pixels, default to `1`.

**New `<as-split-area>` properties:**
* `[minSize]="y"` ⬅️ In selected unit (pixel or percent).
* `[maxSize]="z"` ⬅️ In selected unit (pixel or percent).
* `[lockSize]="true"` ⬅️ Shortcut for `minSize=maxSize=size`.
<hr>

**PERCENT MODE**
Works as today (total sizes should equal `100` else  each size equal `100/nbArea`):
```` html
<as-split unit="percent">
	<as-split-area [size]="30"></as-split-area>
	<as-split-area [size]="40"></as-split-area>
	<as-split-area [size]="30"></as-split-area>
</as-split>
````

**PIXEL MODE**
In this new mode, a wildcard size area is mandatory (and this area can't be set to `[visible]="false"`).
Container size can change, pixel values stays the same, wildcard area grow/shrink.
```` html
<as-split unit="pixel">
	<as-split-area [size]="200"></as-split-area>
	<as-split-area [size]="'*'"></as-split-area>
	<as-split-area [size]="280"></as-split-area>
</as-split>
````
<hr>

**Why doing this:**
Because like this, even when container size changes, without window event listener (doing this would be wrong because we can't presume container is full window, changes could come from layout changes,..), area sizes stays consistent:
* if PERCENT MODE -> Ok no problem, easy for css: `flex: 0 0 calc(X% - Ypx);`
* if PIXEL MODE -> Wildcard area adapt itself thanks to css `flex: 1 1 auto;`
The same happens if we change direction, it works smoothly!

Mixing pixels and percentages would be more complicated with some edge corner cases..
Do you see a real world scenario where mixing percent & pixel for `[size]`/`[minSize]`/`[maxSize]` has an interest?

**Things to clarify:**

In pixel scenario, what happens:
* When container `<as-split>` size go under `480px`?
* What do you expect as sended size values on `(dragStart)`/`(dragEnd)`/.. events and `dragProgress$` observable? percent, pixel? `344/'*'/280`?

I'm waiting for your feedbacks! ;)
I will work on it soon.

**Comment by jacobbutton** [comment]
Awesome. I'm in the process of updating to Angular 7 and my previous forked copy that allowed pixelSize no longer works, so this update would be much appreciated.

> Mixing pixels and percentages would be more complicated with some edge corner cases..
Do you see a real world scenario where mixing percent & pixel for [size]/[minSize]/[maxSize] has an interest?

I can possibly see some use cases for it, but I'm not seeing any that nested as-splits wouldn't solve - one in pixels and the other in percent. That's assuming nested as-splits are possible and that a child as-split would update it's total size and it's split-area children should it's parents containers size change.

**Comment by bertrandg** [comment]
Nice, thanks for your feedbacks.
Yes, nested `as-split` will be automatically "resized" using CSS (without JS).

**Comment by F0rt1s** [comment]
Great ideas, I'd love to see pixel as an unit!

> When container <as-split> size go under 480px?

Maybe collapse the panel (in order), if possible?

> What do you expect as sended size values on (dragStart)/(dragEnd)/.. events and dragProgress$ observable? percent, pixel? 344/'*'/280?

I would expect the values to be in the selected [unit].

**Comment by bertrandg** [comment]
hi @F0rt1s,
Thanks for your feedbacks, ;)

1 Yes I will try to collapse areas if I can, I need to test how `flex-shrink: 1;` behaves because solution needs to be CSS only (no JS listeners on container size).

2 It will be in specified unit but I think, in pixel mode, always returning `'*'` for wildcard size area is important because a classic usecase is to save sizes to provide it again next time split is displayed (and having an area with `'*'` is mandatory).

**Comment by Rush** [comment]
Thank you for working on this. `minSize` would be greatly appreciated.

**Comment by bertrandg** [comment]
Yep, coming soon, you can preview it there (`3.0.0-beta.4`):
https://stackblitz.com/edit/angular-j45ncr?file=src%2Fapp%2Fapp.component.html

**Comment by Nishkalkashyap** [comment]
Hey @bertrandg.  Thank for the awesome library. I was wondering if a feature could be implemented that toggles the split-area visibility at the minSize breakpoint. Perhaps something like this:

![angular-split](https://user-images.githubusercontent.com/32554850/50535919-db028c80-0b74-11e9-9526-3767626ef646.gif)

**Comment by bertrandg** [comment]
@Nishkalkashyap Yes could be nice, I will think how to implement it.

But it will not be there for coming `3.0.0` release. ;)

**Comment by vlodko** [comment]
@bertrandg, first of all, thanks for coming back and taking care of this awesome library!

Q: do you plan to add the ability to project custom stuff inside of the gutter element?
Simple example:
![image](https://user-images.githubusercontent.com/2395824/50791454-20af0b80-127f-11e9-86cc-56114ceaecb0.png)

It could be helpful for cases when we want to add special button to the gutter element for changing direction or collapsing/expanding one of panes.

Thanks

**Comment by bertrandg** [comment]
@vlodko 
Yes good ideas, I keep them for next version (after 3.0.0 release)

**Comment by vlodko** [comment]
@bertrandg what is an ETA on the features I described above? months, weeks?

**Comment by bertrandg** [comment]
In months for dom elements projection inside gutters.. 
Not sure exactly how to do it properly.

But for `dblclick`, it seems simple to add, so more in weeks.

**Comment by vlodko** [comment]
@bertrandg , yes. double click should be easier and really helpful. I got feedback that sometimes on drag it accidentally produces click event which is causing unwanted behavior (collapse/expand of the pane in our case).

about the gutter - it way with with content projection if you add a selector to ng-content in your code

**Comment by Newan** [comment]
Hello,
first thanks for the update and the new features, great.
But still found a problem when embedding an iframe. Then no real resize is possible anymore:
https://stackblitz.com/edit/angular-98qhps?file=src/app/app.component.html

**Comment by bertrandg** [comment]
@Newan Well done, I wasn't remembering it! :)

**Comment by bertrandg** [comment]
@jainaman224 Thanks for your feedbacks. :)

> _minSize_ doesn't work on unit pixel with _wildcard_ size.
> https://stackblitz.com/edit/angular-tamldq

Yes that's normal behavior (I know I need to document it).
I planned to add it at first and had been blocked, _wildcard_ area size changes according to container size.
So a _minSize_/_maxSize_ could be true at component initialization and then, later, after window resize or layout changes it could be wrong state and no way to know it.
So I prefer not implementing it to be sure to have correct state all time..

> I think there is a scenario where we have header in pixel. So, we want `minSize` to be in pixel and `splits` resizing should work according to percentage.
> Although, I can understand the complexity but it will be great to have.

In your scenario, your header with pixel height needs to be possibly enlarge/shrink by user ?
If no, take it out of the split.
If yes, you can embed a percentage split inside a pixel split area like this:
```` html
<as-split unit="pixel" direction="vertical">
  <as-split-area [size]="42">
	<div class="header">XXX<div>
  </as-split-area>
  <as-split-area [size]="'*'">
	<as-split unit="percent" direction="vertical">
		<as-split-area [size]="30">A</as-split-area>
		<as-split-area [size]="40">B</as-split-area>
		<as-split-area [size]="30">C</as-split-area>
	</as-split>
  </as-split-area>
</as-split>
````

I'm gonna work on the library next week, there will be changes soon! ;)

**Comment by Roaders** [comment]
I might be missing it but there doesn't seem to be any support for flex-grow and flex-shrink equivalents for each area.
In all of my use cases we have one view that displays some static info that is usually fairly small and in the other pane we have a grid that we want to take up the rest of the view. I don't want to set a percentage or a pixel size, I want to to set flex-grow on one view.

Is this currently supported or does it have planned support?

Thanks

**Comment by bertrandg** [comment]
@Roaders 
Hi, this library is made specifically to split a container into multiple areas using pixels or percentages values and then allow users to drag separators to update those values.

So no, there is no option to work as you describe and no plan to.. 
but do you need to allow users to update areas sizes? If not, just use css flex grid..

**Comment by HugzM** [comment]
Hello Bertrand and first of all thanks for this awesome library you're working on .
Question : do you have a release date for the v3 ?

**Comment by bertrandg** [comment]
@HugzM 
thanks, I think i will publish an RC next week.

**Comment by vdjhards** [comment]
Angular split not working within angular material tabs content properly.
I had tried using your both angular-split version 2 and your beta version 3

`
<mat-tab-group>

    <mat-tab label="First">

        <as-split style="height: 300px;" unit="percent">
            <as-split-area size="30">
                <p>A</p>
            </as-split-area>
            <as-split-area size="40">
                <p>B</p>
            </as-split-area>            
        </as-split>
    </mat-tab>
    <mat-tab label="Second"> Content 2 </mat-tab>
    <mat-tab label="Third"> Content 3 </mat-tab>
</mat-tab-group>
`
The below screen shot is of beta version3 with angular material 7
"as-split-area" size of left content it is not getting width as set to 30%

![width-error](https://user-images.githubusercontent.com/42489589/54262009-2ed91b00-4593-11e9-8d7d-6f16d36c9c31.JPG)

**Comment by bertrandg** [comment]
hi @vdjhards 
Please open a separate issue with a stackblitz example showing your problem.

**Comment by lukaszbachman** [comment]
@bertrandg very cool that you are close to getting this done :) I think it will be very handy feature which fits most of use cases where angular-split is being used.

I'm currently trying to do exactly the same thing that @Nishkalkashyap showed in his screendump. I guess that will be another common use case when angular-split is being used for sidebar menus.

Great work!

**Comment by bertrandg** [comment]
@lukaszbachman Thanks, that's noted! ;)

**Comment by jakobvinther** [comment]
Please excuse me if this is not the right place to ask. Is it possible to get the width and height (in pixels) of an as-split-area after the dragEnd() event? I need it to explicitly resize a child element (a chart).

**Comment by lukaszbachman** [comment]
@jakobvinther I'm dong the same by subscribing to `dragEnd` and calculating the PX size by multiplying the percentage value times the window's width.

**Comment by jakobvinther** [comment]
Okay thanks, I got it to work too!

**Comment by BlindDespair** [comment]
Hello, I also have a question about release date, do you plan to release v3 any time soon? It doesn't need to be an exact date, it will just help me plan my work, because my team seems to vote toward this library (if it's not going to be soon, then we'll go for v2). Thank you.

**Comment by CheNMorD** [comment]
Hi  @bertrandg, when the version with limited drag will be released?
for example, [minSize]="10" [maxSize]="20".
thanks.

**Comment by bertrandg** [comment]
@BlindDespair @CheNMorD @HugzM 
New version `3.0.0` just been released! ;)

**Comment by vlodko** [comment]
@bertrandg you rock, man!

**Comment by ashishbhatia1995** [comment]
@bertrandg can we do 1 scroll for both the screens. If content overflow I am getting different scrolls. But need 1 scroll to scroll both screens at once in as-split. Can u please help. Need this urgent.

**Comment by beeman** [comment]
Hey @ashishbhatia1995, Bertrand is no longer maintaining this library. For support you can use the Discord channel linked in the readme.
