### ISSUE TITLE
Angular-Split Not Working CDK Template

### ISSUE THREAD

**Issue by hugoebarboza** [bertrandg/angular-split#136]
Hi,

My code, angular-split not working. What can I do ?

<ng-template cdkPortal #myTemplate2="cdkPortal" >
<div style="height: 768px">
    <as-split direction="horizontal">
        
        <as-split-area size="70">
        <ng-container [cdkPortalOutlet]="_home" ></ng-container>
        </as-split-area>
        
        <as-split-area size="30">
        <div class="p-2">
        <app-vieworderdetail [orderid]="order_id"></app-vieworderdetail>
        </div>
        </as-split-area>

   </as-split>          
</div>

</ng-template>

**Comment by bertrandg** [comment]
You can create a stackblitz to demonstrate your issue.

**Comment by hugoebarboza** [comment]
Hi,

https://stackblitz.com/edit/angular-cdk-portal-simple-example-kryycg

**Comment by bertrandg** [comment]
I've take a look and you are using angular `4.x`, angular-split needs `7.x`:
https://unpkg.com/angular-split@2.0.0/package.json

**Comment by hugoebarboza** [comment]
Hi, thanks for your help, I am using angular 7.1.4 in my localapp.

**Comment by hugoebarboza** [comment]
Hi, thanks for your help, I am using angular 7.1.4 in my localapp and the split does not working.

**Comment by hugoebarboza** [comment]
Ok, thanks for your help.
https://stackblitz.com/edit/angular-cdk-portal-simple-example-kryycg

**Comment by bertrandg** [comment]
Sorry but all `@angular/*` should be versions `7.x` to have a chance to works.

**Comment by hugoebarboza** [comment]
Hi, there you go. Anything else ?

https://stackblitz.com/edit/angular-cdk-portal-simple-example-kryycg

**Comment by bertrandg** [comment]
Ok, I checked it and using angular-split `2.0.1` , you just need to import module like this:

``` js
@NgModule({
  imports: [
    AngularSplitModule.forRoot(),
    BrowserModule, 
    FormsModule,
    PortalModule,
  ],
  declarations: [
    AppComponent
  ],
  bootstrap: [
    AppComponent
  ],
  entryComponents: [
  ]
})
export class AppModule { }
```

And it works!

**Comment by hugoebarboza** [comment]
Hi, thanks a lot, finally it works!!! I am greatfull....
