### ISSUE TITLE
Feature request: Gutter double click event

### ISSUE THREAD

**Issue by vasiltabakov** [bertrandg/angular-split#138]
Would be great to have it, thanks

**Comment by bertrandg** [comment]
I've just published `angular-split@3.0.0-beta.9` which solve mobile `(gutterClick)` event not fired #145 and add `(gutterDblClick)` event.

Check demo there:
https://stackblitz.com/edit/angular-xztkig?file=src%2Fapp%2Fapp.module.ts

**Comment by bertrandg** [comment]
Note that a new param is needed to have double click working:
`````html
<as-split gutterDblClickDuration="500" (gutterDblClick)="xxx($event)">
  ...
</as-split>
`````

**Comment by sbervinov** [comment]
Looks like gutterDblClick does not work. It does not work in my project and it does not work in your demo (https://stackblitz.com/edit/angular-xztkig?file=src%2Fapp%2Fapp.module.ts)
