### ISSUE TITLE
How to use with systemjs

### ISSUE THREAD

**Issue by ducmaxime** [bertrandg/angular-split#14]
Hi,
Do you know how include import in systemjs config ?

thx

**Comment by bertrandg** [comment]
hi,

Yes, did you see the website: https://bertrandg.github.io/angular-split/

Test that and let me know:
```javascript
System.config({
  ...
  map: {
    ...
    'angular-split': 'node_modules/angular-split/dist/index.js'
  }
});```

**Comment by ducmaxime** [comment]
Yes, it's work, but this generate new error 

http://localhost:5555/node_modules/traceur.js Failed to load resource: the server 

any idea ?

**Comment by bertrandg** [comment]
No idea..
Test removing `angular-split` from your project to check if it comes from it.

This plunker shows it using `systemjs`:
https://plnkr.co/edit/tEjcXo?p=preview

**Comment by ducmaxime** [comment]
It was an other error on my project. Its work fine now !!!!

resume : 

1. npm install angular-split --save
2. add in systemjs config paths : 
'angular-split' : 'node_modules/angular-split/dist/index.js',
3 add in systemjs config     packages: 
 'angular-split': {
        defaultExtension: 'js'
  }

Thx for your help !!

**Comment by bertrandg** [comment]
cool :)

**Comment by SergejPanov** [comment]
Hi @ducmaxime,

Could you, please, advise, what was the problem in your case? I have the same issue and can not figure it out - it appears only if I add angular-split in the mappings

Thanks,
Sergey

**Comment by ducmaxime** [comment]
Hi,

just add traceur ref in your systemjs config like this:

'traceur' : 'node_modules/traceur/bin/traceur.js',

**Comment by hem19** [comment]
I have a working app using SystemJS. When I added the 'angular-split' package and included 'AngularSplitModule' in app.module.ts and updated Systemjs.config.js as suggested, I too started getting error for 'traceur'.
There is no reference of 'traceur' anywhere in the project. Then I specifically added 'traceur' in package.json but still it is throwing following errors:

GET http://localhost:3000/node_modules/angular-split/dist/angularSplit.module 404 (Not Found)
GET http://localhost:3000/node_modules/angular-split/dist/split.component 404 (Not Found)
GET http://localhost:3000/node_modules/angular-split/dist/splitArea.directive 404 (Not Found)
GET http://localhost:3000/node_modules/angular-split/dist/splitGutter.directive 404 (Not Found)

**Comment by ducmaxime** [comment]
You have to add traceur import in systemjs:

'traceur'  'node_modules/traceur/bin/traceur.js'},
