### ISSUE TITLE
Can't find Angular 6 compliant version

### ISSUE THREAD

**Issue by victordraganov** [bertrandg/angular-split#140]
Hello. Currently I am trying to migrate a project to Angular 6. I have a nested npm module which uses AOT and I can't seem to get it working. I couldn't find angular-split version released specifically for Angular 6 support and maybe that is the issue I am facing.

Getting these kinds of errros when `ngc -p tsconfig-aot.json`

```
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
: Can't bind to 'size' since it isn't a known property of 'split-area'.
1. If 'split-area' is an Angular component and it has 'size' input, then verify that it is part of this module.
2. If 'split-area' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <split direction="vertical" class="vertical-split">
            <split-area [ERROR ->][size]="10" [visible]="hasValidationResult">
                <cf-element-issues [fieldId]="field?.id"")
: Can't bind to 'visible' since it isn't a known property of 'split-area'.
1. If 'split-area' is an Angular component and it has 'visible' input, then verify that it is part of this module.
2. If 'split-area' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <split direction="vertical" class="vertical-split">
            <split-area [size]="10" [ERROR ->][visible]="hasValidationResult">
                <cf-element-issues [fieldId]="field?.id"></cf-elemen")
```

AngularSplitModule is properly added as an NgModule and I can't seem to find the issue. Migrating to Angular 7 is not an option for me.

Looking at the repo angular-split migrated directly from Ang5 to Ang7.

**Comment by bertrandg** [comment]
Hi,
Check this [stackblitz ](https://stackblitz.com/edit/angular-4cnpkr?file=src%2Fapp%2Fapp.component.html)using `angular/*@6.1.10` and `angular-split@2.0.0` working together.
I've downloaded files and installed it locally to test a `ng build --prod --aot true` and it works.

You're right for `angular-split@2.0.1`, it doesn't work for angular 7.

**Comment by victordraganov** [comment]
Sorry for the big delay on this. I managed to get it working with 1.0.0-rc.3
