### ISSUE TITLE
Angular Split inside router-outlet

### ISSUE THREAD

**Issue by jainaman224** [bertrandg/angular-split#141]
I am using angular split inside my root component then it is working but when I move this code to component rendered using `router-outlet`. Drag event doesn't work.

```
<div style="height: 100%; width: 100%">
  <as-split [direction]="'horizontal'" [gutterSize]="10">
    <as-split-area [order]="1" [size]="30">
      <div>
        hello
      </div>
    </as-split-area>
    <as-split-area [order]="2" [size]="70">
      yellow
    </as-split-area>
  </as-split>
</div>
```

Used this code, in both the cases.

**Comment by bertrandg** [comment]
Please create a stackblitz to demonstrate it.

**Comment by mjbezanson-cob** [comment]
I just upgraded yesterday as part of my Angular 7 update.  I had the same issue - drag not working.  The issue for me was that I didn't add the .forRoot() to the AngularSplitModule import in my app module.  

See the 2.0.1 note here:
https://bertrandg.github.io/angular-split/#/changelog

**Comment by jainaman224** [comment]
Thanks @mjbezanson-cob, I haven't upgraded the package it is still version 2.0.0 but I think it is some other issue with my code. In new project, it is working great.

Sorry @bertrandg for raising the issue.

**Comment by jainaman224** [comment]
They issue was, it requires to import `angular-split` in `app.module` as well in addition to other modules.
