### ISSUE TITLE
Datepicker in SplitArea / visibility

### ISSUE THREAD

**Issue by MatraiGergo** [bertrandg/angular-split#144]
Hi,
i have a datePicker ( prime-ng calendar) in a splitArea, it is possible to somehow make the datepicker always visible?

![image](https://user-images.githubusercontent.com/22551937/52418181-c7d8ca00-2aed-11e9-9fb2-081f19fc2df3.png)

i tried with CSS, but nothing works, I'm beginner maybe I'm just missed something.
Thx for the help: 
Gergő

**Comment by jacobbutton** [comment]
This isn't an angular-split problem. angular-split is acting as expected here.

prime-ng has an appendTo property to change the target element that the overlay to. Try setting that property to "body"

**Comment by MatraiGergo** [comment]
Hi , 

appendTo="body" 

solved the problem. 

And sorry, I know this was not the correct place for this type of question. I just not found the correct answer anywhere. 

So Thx :)
