### ISSUE TITLE
Vertical splits- if the top split area is init as hidden when you toggle visibility it will appear as the bottom split area

### ISSUE THREAD

**Issue by rpatinki** [bertrandg/angular-split#146]
Here is the [stackblitz](https://stackblitz.com/edit/angular-sjz28t?file=src%2Fapp%2Fapp.component.html) use the toggle button to toggle the top split area visibility. 

**Expected behavior:** split area should be presented in the order they are created in the template, even if some of them initialized with visibility hidden.

**Current behavior:** When the top split area is initialized as hidden and then the visibility is being updated to true. the bottom split area is presented as the top split area.

**Comment by bertrandg** [comment]
I know it could be weird but that's normal behavior and I don't plan to change it soon.

Currently to avoid this you have to use `[order]` property like this:
````html
  <as-split [direction]="'vertical'">
      <as-split-area size="30" order="1" [visible]="vis">
          <p>This should be the top split area</p>
      </as-split-area>
      <as-split-area size="70" order="2">
          <p>This should be the bottom split area</p>
      </as-split-area>
  </as-split>
