### ISSUE TITLE
Gutter not keeping move after one as-split is hidden

### ISSUE THREAD

**Issue by mdewell** [bertrandg/angular-split#147]
Hello Bertrand,

Angular Split is a great tool, and this may be a quick answer for you, but I have a problem with splits not keeping there size.  I have three panes.  One is hidden and the other two are visible on the initial display.  When the hidden pane is still hidden, it seems that the other two panes don't keep their resize.  If I unhide the third pane, the panes keep their resizes.   Here is a stackblitz for it:

https://stackblitz.com/edit/angular-hqwk2g

Thank You

**Comment by mdewell** [comment]
Nevermind!  Got it.  it needed the dragEnd to be input and output, in the as-split defining lines.

<as-split [direction]='direction' disabled="false" [useTransition]="action.useTransition" ([dragEnd])="action.treeSize=$event.sizes[0]; action.documentSize=$event.sizes[1]; action.graphSize=$event.sizes[2];">

not just:

<as-split [direction]='direction' disabled="false" [useTransition]="action.useTransition" (dragEnd)="action.treeSize=$event.sizes[0]; action.documentSize=$event.sizes[1]; action.graphSize=$event.sizes[2];">

i.e. ([dragEnd]) not just (dragEnd)

Sorry and thanks a gain for the tool.

**Comment by bertrandg** [comment]
Hi @mdewell ,
Nice if it works as you want but `([dragEnd])` is not a working syntax with angular-split..
There is only an event named `dragEnd` but no property in this library.

**Comment by mdewell** [comment]
Hmmm.  I'm not sure why it works then. 😃   Thanks for the reply.
