### ISSUE TITLE
Using AngularSplit in a sub module requires use of undocumented forChild()

### ISSUE THREAD

**Issue by corvinrok** [bertrandg/angular-split#149]
In using AngularSplitModule, I could import and access it in the app-module level no problem. However, I wanted to also use it in a child module deep in the hierarchy. This is not clear or documented how to do so. After much searching,  I found I needed my child module to access it via:

```
import {AngularSplitModule} from 'angular-split';

@NgModule({
    imports: [
        AngularSplitModule.forChild(),
```

This needs to be documented for consistency and to help save time.  I spent hours trying to figure out how to get use of `as-split` and `as-split-area` in child modules.

**Comment by bertrandg** [comment]
I've just released 3.0.0, check demos using lazy loading:
https://bertrandg.github.io/angular-split/#/examples/lazy-loaded-module

forRoot/forChild methods are still there but not needed anyore:
https://github.com/bertrandg/angular-split/blob/master/projects/angular-split/src/lib/module.ts
