### ISSUE TITLE
traceur 404 issue after adding the library

### ISSUE THREAD

**Issue by SergejPanov** [bertrandg/angular-split#15]
I am having the issue that traceur could not be loaded after importing the library (HTTP 404):

In mappings in system.config.js I have the following to define the angular-split as per manual:

'angular-split': 'node_modules/angular-split/dist/index.js

traceur is not even referenced as dependency anywhere in my project, not sure why I get this error

**Comment by bertrandg** [comment]
No idea but in this previous issue, someone had similar error using `systemjs`: https://github.com/bertrandg/angular-split/issues/14

Follow instructions from @ducmaxime in his last message. Maybe you just need to add:
```
'angular-split': {
  defaultExtension: 'js'
}

**Comment by SergejPanov** [comment]
Thanks, I will follow up with the #14

**Comment by bertrandg** [comment]
cool ;)
