### ISSUE TITLE
how i can limit the split area 

### ISSUE THREAD

**Issue by khaled26** [bertrandg/angular-split#150]
how i can set a max -size and min size to the as-slplit- area ? i have wasted long tome on it .. but nothing worked for me .
it's really urgent.

Thanks

**Comment by bertrandg** [comment]
Use "next" version `3.0.0-beta.9` and read about it there: https://github.com/bertrandg/angular-split/issues/131

**Comment by khaled26** [comment]
i am already using it , but it's not working with pixels .. it dosn't care to the numbers i am giving .

**Comment by bertrandg** [comment]
Provide a stackblitz demo if you need help

**Comment by khaled26** [comment]
here is what i have : 
 <as-split  direction="horizontal" [useTransition]= "true" unit="pixel" (dragEnd)="dragEnd($event)" gutterSize="5">
<as-split-area  size="300" minSize="200" maxSize="600" class="pl-2" [visible]="layout.filter || layout.search || layout.peerReview || layout.messageDetails || layout.messageDetailsGrid">
      <mvcm-filter-criteria [ngClass]="layout.filter ? 'visible' : 'hidden'" (close)="layout.filter = false"></mvcm-filter-criteria>
      <mvcm-search-criteria [ngClass]="layout.search ? 'visible' : 'hidden'" (close)="layout.search = false"></mvcm-search-criteria>
      <mvcm-peer-review [ngClass]="layout.peerReview ? 'visible' : 'hidden'" (close)="layout.peerReview = false"></mvcm-peer-review>
      <mvcm-message-details (layoutUpdate) = "layout = $event" [ngClass]="layout.messageDetails || layout.messageDetailsGrid  ? 'visible' : 'hidden'"></mvcm-message-details>
    </as-split-area>
  </as-split>



it's not caring to the numbers of pixels i am giving

**Comment by bertrandg** [comment]
Just tried simplest minSize/maxSize demo and it works well:
https://stackblitz.com/edit/angular-o9ctfe?file=src%2Fapp%2Fapp.component.html

Fork it and add your logic to show me what you want to do..

**Comment by IdiomaSoftware** [comment]
I was having the same issue - I see the problem was that I wasn't setting size to "*" for the second split area. Thanks for the demo!!! One snippet worth 1000 words :).
