### ISSUE TITLE
Latest angular 4 compliant version

### ISSUE THREAD

**Issue by infamousNerd** [bertrandg/angular-split#151]
Again, this is just a question. Our project is  struck at Angular 4 and are reluctant to upgrade right now. They are using a version 0.2.2 for angular-split. I know the latest version is not compatible with Angular 4. I want to know how far through the releases are compatible with ^4.0.0 of Angular, so that I can recommend the latest compatible version angular-split.

**Comment by bertrandg** [comment]
I think `0.2.7` should be working but if it works as expected with `0.2.2` i advice you to stay with it.
Sorry to not help you more but it's old stuff and it was a total mess (this repo and the way to provide angular library) at that time.
As this library doesn't have any security concerns, keep your version and you will update to coming 3.x version when you will update your app to angular 7/8.
