### ISSUE TITLE
Dragging stopped working with 2.0.0-beta.5 and after with Ionic 4

### ISSUE THREAD

**Issue by JoeBoxr** [bertrandg/angular-split#153]
Hello.

Angular Split works great with Ionic 4 but the ability to drag the gutter stopped working with version 2.0.0-beta.5 and later.

Steps:
1. install Ionic 4 following the steps at https://ionicframework.com/docs/installation/cli
2. create a sample app (ie. ionic start myApp tabs)
3. install latest version of Angular Split and add it to one of the tabs on the sample app.

Regards

**Comment by bertrandg** [comment]
Hi, thanks to report.

Did you try with 3.x version (currently `3.0.0-beta.9` but release coming soon)?
Because i changed many things.

**Comment by JoeBoxr** [comment]
Hello.

Yes version 3.0.0-beta.9 worked great.  Thank you
