### ISSUE TITLE
Angular split not working properly when integrated in angular material tabs inside tab-content

### ISSUE THREAD

**Issue by vdjhards** [bertrandg/angular-split#155]
I am using Angular material tabs and inside the first tab i m putting the angular split but it won't fetch the size for the first <as-split-area>. It takes 100% of the last '<as-split-area>
![sp2](https://user-images.githubusercontent.com/42489589/54334439-0d883580-464c-11e9-9908-7fa87d670249.JPG)
'
I had tried using your angular-split version 2.
https://stackblitz.com/edit/angularsplit-splitarea-width-error

As you can see in above example that first "<as-split-area>" size is  set to "30" but it won't fetch the size

**Comment by bertrandg** [comment]
Thanks for creating the issue.

I tried your stackblitz, you're right it fails using `2.0.1` but if you install `3.0.0-beta.9` it works!
I don't think i'm gonna update 2.x but 3.0.0 release is soon..

I'm not used to angular material but i've seen weird behavior regarding split height so I made some tests and got this:
https://stackblitz.com/edit/angularsplit-splitarea-width-error-ax1mtj?file=src%2Fapp%2Fapp.component.css

**Comment by mflorence99** [comment]
FYI I saw a similar issue using `angular-material` and `angular-split 2.x`. In my case, the gutter was immobile and would not drag at all to resize. Following @bertrandg 's hint, I switched to `3.0.0-beta.9` and the problem went away.

Please let me add that `angular-split` is a first-class library. We use it in a number of projects, both open source and in-house. Many thanks @bertrandg and looking forwards to v3!

**Comment by bertrandg** [comment]
@mflorence99 Thanks, I appreciate! ;)

**Comment by bertrandg** [comment]
Version `3.0.0` released, it should works better now! ;)
