### ISSUE TITLE
scroll issue with a 'div' element

### ISSUE THREAD

**Issue by gcjjyy** [bertrandg/angular-split#158]
You can find the issue below link.
In the link page,
When you're scrolling up the right bottom pane repeatedly,
right middle pane will be scrolled up.

https://stackblitz.com/edit/angular-split-issue

**Comment by bertrandg** [comment]
Not sure to understand what you want..

what about this:
https://stackblitz.com/edit/angular-split-issue-zqyoeu?file=src/app/app.component.html

**Comment by gcjjyy** [comment]
@bertrandg Oh! my issue has fixed in your link!

**Comment by gcjjyy** [comment]
**style="display: flex; flex-direction: column;"** has solved this issue.

**Comment by bertrandg** [comment]
Cool ;)
