### ISSUE TITLE
How to change size of an split area programmatically.

### ISSUE THREAD

**Issue by naumanumer** [bertrandg/angular-split#16]
I want to resize an split area dynamically from typescript is there any way??

**Comment by bertrandg** [comment]
yes, check out the website, you have examples:
https://bertrandg.github.io/angular-split/

And the code is viewable here:
https://github.com/bertrandg/angular-split/tree/website-src

**Comment by naumanumer** [comment]
Actually i want to change size by px not %

**Comment by bertrandg** [comment]
You can't set it in pixel currently.

**Comment by nagrito** [comment]
And now is it possible to set it in pixels ?
