### ISSUE TITLE
Incorrect area sizes when initially not visible

### ISSUE THREAD

**Issue by igor-t** [bertrandg/angular-split#161]
When split container (as-split) is hosted within 'mat-tab' (Angular Material tab) and that tab initially is not active/visible then sizes for areas calculated as [0, 0, 0,...100].
Sizes set by 'size' property of 'as-split-area' are ignored.

**Comment by bertrandg** [comment]
Please provide a stackbitz demo.

**Comment by igor-t** [comment]
Working on it.

**Comment by igor-t** [comment]
Here's the demo:
https://stackblitz.com/edit/angular-split-in-tab

**Comment by bertrandg** [comment]
Thanks,
Yes there's something wrong that has been corrected in 3.x branches, just install version `3.0.0-rc.0`.
`3.0.0` release is coming soon.

**Comment by igor-t** [comment]
Works as expected with 3.0.0-rc.0

Thanks!
