### ISSUE TITLE
Is there a way to have the split change just visibility of the as-split-area and not resize their contents?

### ISSUE THREAD

**Issue by ramonjsantiago** [bertrandg/angular-split#162]
I'm  trying to use this for a split between a before-and-after image comparison.
Something like the splitter seen on this page; https://topazlabs.com/

**Comment by bertrandg** [comment]
Hi @ramonjsantiago,
Your case is interesting, 
this is not the purpose of this library but I will see if I can code an example using current version..

**Comment by ramonjsantiago** [comment]
I ended up doing this by hand instead of using angular-split.
My Use Case is this; A top panel with a non-resizeable ESRI map, a bottom panel with Google Street View that does need to resize.
I was able to make the top panel's contents not-resize, but then I also need all events to be passed to the ESRI map.

**Comment by bertrandg** [comment]
Yes I understand, that's a better solution to code it than twist `angular-split` to your usecase..
