### ISSUE TITLE
When changing the size to percentage (style="width: 100%;") the resize functionality isn't working!

### ISSUE THREAD

**Issue by zbeedatm** [bertrandg/angular-split#165]
If set the Width, Height to pixels the resize functionality works... when changing it to percentage it's not.

**Comment by bertrandg** [comment]
Please provide a stackblitz demo.

**Comment by bertrandg** [comment]
Feel free to reopen if you provide a demo..

**Comment by danyhoron** [comment]
Here's an example:
https://stackblitz.com/edit/angular-split-demo-wbwwma?file=src/app/app.component.html
On app.component.html I changed width and height to `%` instead of `px`.

**Comment by beeman** [comment]
Hey @danyhoron, in your example the behavior is fixed when you set this in the global styles.css:

```css
html, body {
  height: 100%
}
```

This is because of heights work in html, it needs 100% height on the parent too in order for it to work as expected.

Hope this helps.

**Comment by danyhoron** [comment]
You're right. It  works.

Thank you.
