### ISSUE TITLE
Angular Split not working with lazy loading

### ISSUE THREAD

**Issue by nelitonmateus** [bertrandg/angular-split#168]
I updated my project to use lazy loading and the angular split stopped working,
It isn't showing any errors on console.
I have one splitter and the page is showing it but when I try to move it, it doesn't work, I can't move to any direction

**Comment by bertrandg** [comment]
hi,
there's known issues with 2.x, it should be corrected using `3.0.0-rc.0`.
Which version are you using?

**Comment by DavoBR** [comment]
Hi, the workaround that i using is removing the `as-split-undetected.`  in the template of angular-split module

**Comment by bertrandg** [comment]
In version `3.0.0-rc.0`, there is no more custom event executing outside zone.
It was over-engineered and leaded to issues, lazy-loaded modules was one of these.. so just use latest version, it should works.

**Comment by bertrandg** [comment]
I've just released `3.0.0`, check demos using lazy loading:
https://bertrandg.github.io/angular-split/#/examples/lazy-loaded-module
