### ISSUE TITLE
Box shadow in class as-split-area

### ISSUE THREAD

**Issue by celestale** [bertrandg/angular-split#169]
I tried to add box shadow to the split areas but it is not showing up.

Class `as-split-area` by default contains `order: X and flex-basis: X`. It doesn't seems to work if I add box shadow `0px 1px 4px red` in this class. How can I add a shadow around each split area to make it not look so flat?

**Comment by bertrandg** [comment]
hi @celestale,

You need to override `as-split` container `overflow: hidden` css rule and remove `as-split-gutter` background-color to display a box shadow correctly.

check this demo:
https://stackblitz.com/edit/angular-jrjzit?file=src%2Fapp%2Fapp.component.css

**Comment by celestale** [comment]
Hi bertrandg, your explanation is very helpful. Thanks for the help!
