### ISSUE TITLE
Inside split-area, div height:100% is incorrect on Safari

### ISSUE THREAD

**Issue by xwb1989** [bertrandg/angular-split#17]
On Safari, if we have a `div` inside `split-area` and set its `height` to `100%`, its `height` be will the same as the `height` of `split` instead of `split-area`. Therefore the `div` could just overflow the `split-area`. This does not happen on Chrome.

To demonstrate the problem, I have forked the site examples and here is the code snippet: 

https://github.com/xwb1989/angular-split/blob/website-src/src/app/examples/examples.route.component.html#L11

Build the site and open it in Safari and Chrome, you will see the difference.

**Comment by bertrandg** [comment]
Thanks to report it, I will test it asap.

**Comment by lasimone** [comment]
+1
