### ISSUE TITLE
Possible to disable certain gutter

### ISSUE THREAD

**Issue by celestale** [bertrandg/angular-split#170]
Hi, it is possible to disable certain gutter and leave the others enabled?

Current API - `@Input() disabled` this will disable all gutters for dragging.

**Comment by Shemesh** [comment]
i was in need for this functionality as well - it does not exist in the current version :-(
you can see my [pull request](https://github.com/bertrandg/angular-split/pull/167) where i have added a code to do this.
hopefully @bertrandg will merge it soon
