### ISSUE TITLE
Add support for Angular 8

### ISSUE THREAD

**Issue by paustint** [bertrandg/angular-split#175]
# Description
I would like the peer dependency to be updated to support Angular 8 as well as any other changes required for the library (e.x. `@ViewChild` `@ContentChild`).

https://github.com/angular/angular/blob/master/CHANGELOG.md

![image](https://user-images.githubusercontent.com/5461649/58600660-c0773100-8242-11e9-8aac-35b203c9fa57.png)

**Comment by zerocewl** [comment]
Any news on this?

**Comment by bertrandg** [comment]
Done, try `8.0.2` ;)
