### ISSUE TITLE
I made an Angular Size Observer library which pairs well with angular-split

### ISSUE THREAD

**Issue by thefliik** [bertrandg/angular-split#176]
Thanks again for making this library, it's super useful!

A while back I had a need to update portions of my layout within an `angular-split` component based on the displayed width of a `split` pane. Kinda like a css media query, except based on the pane's displayed size in the browser, rather than the window's screen size (incidentally, there's a long stalled proposal for a [CSS element query](https://github.com/tomhodgins/element-queries-spec) spec which would address this, but alas, it doesn't exist).

I ended up making an [Angular Size Observer](https://gitlab.com/service-work/size-observer) library to solve this problem that works quite well and I just published it. The Angular Size Observer library isn't tied to angular-split in any way, and I'm sure there are many use cases for it that have nothing to do with angular-split, but I thought I'd share it here because I think it plays really nicely with your library.

And again, thanks for making this!

Feel free to close this issue, it's just an FYI.

You can find Angular Size Observer here: https://gitlab.com/service-work/size-observer

**Comment by bertrandg** [comment]
Hi @thefliik, thanks.
Just take a look at your library, that's interesting!
But for me, currently, browser compatibility for ResizeObserver is still too bad to implement it in a real app:
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by thefliik** [comment]
@bertrandg yes, [I call out the likely need for a polyfill](https://gitlab.com/service-work/size-observer#angular-size-observer) in the install instructions. The practical effect of this is that the library is [1.3 kb larger](https://bundlephobia.com/result?p=resize-observer@1.0.0) than it would otherwise be. Which I imagine is fine for most apps using `angular-split` (I imagine this component is generally used in a desktop setting).

**Comment by bertrandg** [comment]
oh yes that's cool, size isn't an issue, sure.
But i'm more curious about performance for this type of polyfill, I imagine it checks frequently if size changed but how frequently? a timer?

Anyway, that's interesting, thanks for sharing ;)

**Comment by thefliik** [comment]
For those interested, I chose the [`resize-observer`](https://github.com/pelotoncycle/resize-observer) polyfill for my own app because it is written in typescript. It seems to rely on a continuous polling loop (which hasn't been an issue for me). The more popular [`resize-observer-polyfill`](https://github.com/que-etc/resize-observer-polyfill) spends a bit of time talking about it's [observation strategy and performance](https://github.com/que-etc/resize-observer-polyfill#observation-strategy) which makes use of a MutationObserver to avoid the need for continuous polling.
