### ISSUE TITLE
Styles lost when hosting application set to ViewEncapsulation.None

### ISSUE THREAD

**Issue by greggbjensen** [bertrandg/angular-split#178]
**Describe the bug**
In our application we default the view encapsulation to none to be able to more easily support customer skins in CSS.  This causes angular-split to loose it's style. 

```ts
platformBrowserDynamic().bootstrapModule(AppModule, [
  {
      defaultEncapsulation: ViewEncapsulation.None
  }
])
```

**To Reproduce**
1. Create a new Angular application
2. Set default encapsulation to None

https://stackblitz.com/edit/angular-mbhnje

Here is the pull request for the fix: #177

**Comment by beeman** [comment]
@greggbjensen thanks for creating the issue and the fix, it got merged today. 

Could you verify if this works in `angular-split@4.0.0-beta.0`?
