### ISSUE TITLE
Gutter behavior in Firefox 67.0.4 (latest)

### ISSUE THREAD

**Issue by garyw90** [bertrandg/angular-split#179]
There seems to be some strange behavior with the gutter (and one of the panes) in Firefox 67.0.4 (latest).  I am using angular-split 3.0.2 (latest).  This works fine in IE 11 and Chrome.

When the browser is full screen, the gutter appears.

When the browser is not full screen, the gutter does not appear.

However, if I go to inspect the right pane in the Firefox debugger, the gutter appears.  Also, if I refresh the page, then drill down at some point the gutter appears, all without refreshing the page, or touching anything else in the UI.

this first image shows what it looks like when it fails
![Capture 2019-07-03-1551](https://user-images.githubusercontent.com/8755964/60629490-d1b7de00-9daa-11e9-9d06-9dc6160c818f.PNG)

This next image shows what it is supposed to look like (and does in full screen mode in Firefox)
![Capture 2019-07-03-1552](https://user-images.githubusercontent.com/8755964/60629544-fb710500-9daa-11e9-9ef6-8f5ac17cb54b.PNG)

The HTML looks like this:
![Capture 2019-07-03-1557](https://user-images.githubusercontent.com/8755964/60629616-45f28180-9dab-11e9-83af-bc9ebcdb2e1b.PNG)

And the CSS like this:
![Capture2019-07-03-1558](https://user-images.githubusercontent.com/8755964/60629661-75a18980-9dab-11e9-9b2c-3d740463b678.PNG)

Any insight would help.  Thanks for a great component!

**Comment by bertrandg** [comment]
Please provide a stackblitz demo.

**Comment by garyw90** [comment]
Attached in a zip file that demonstrates the problem.  To see the issue, click on the icon on the left navigation bar for 'Users'.  Then click the first user ('John Doe'), notice the gutter appears.  Click the second user ('Sue Smith') and notice the gutter disappears.  This appears to be related to the scroll bar on the left pane, as observed in our full application. Note this works properly in Chrome and IE 11 (our company is slow)

[split.zip](https://github.com/bertrandg/angular-split/files/3370548/split.zip)
