### ISSUE TITLE
Angular-Split with SemanticUI sidebar

### ISSUE THREAD

**Issue by sushanzh** [bertrandg/angular-split#18]
Hi,

I installed the angular-split via npm, and in my app.module.ts, I added the following... It worked at first, by simply adding <split direction="horizontal"><split-area [size]="30">...my code here ...  </split-area><split-area [size]="70">...my code here ... </split-area></split> . The screen separator works like a charm. But since I am using the sidebar component of Semantics UI which is my front-end framework, the split panel stopped working. My suspicion is that the sidebar automatically adds class="pusher" to the body tag after the sidebar is clicked on, and that conflicts with the angular-split.

Do you have any ideas on how to go about resolving this issue? 

import { AngularSplitModule } from 'angular-split';
@NgModule({
  imports: [
   ...
    AngularSplitModule
   ...
  ],

**Comment by bertrandg** [comment]
Hi,
Hard to say.. I've never used semanticUI.
Please provide me a plunker (start from this one https://plnkr.co/edit/tEjcXo?p=preview). ;)

**Comment by bertrandg** [comment]
Need a demo (stackblitz or plunker) if you want help.
I close the issue and will reopen it if you provide me one.
