### ISSUE TITLE
cannot display the ag-grid

### ISSUE THREAD

**Issue by junix2020** [bertrandg/angular-split#180]
**Describe the bug**
Please specify library version.

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
https://stackblitz.com/

**Comment by jun-la** [comment]
<as-split-area size="60">
<div>
<router-outlet></router-outlet>
 </div>
</as-split-area>
the problem is it cannot display the ag-Grid component together with the data in the right pane.

**Comment by jun-la** [comment]
do have any idea how to solve it?
the problem is it cannot display the ag-Grid component together with the data in the right pane.

**Comment by bertrandg** [comment]
Please provide a stackblitz demo.
