### ISSUE TITLE
Resizing iframe will cause lose drag-end event

### ISSUE THREAD

**Issue by Mike-Jia** [bertrandg/angular-split#181]
**Describe the bug**
When I use a **iframe** in **as-split-area**, drag gutter to the iframe side fast and release the mouse button, gutter bar will move with mouse all the time.

"angular-split": "^3.0.1".

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
open https://stackblitz.com/edit/angular-rcqyv1
and replace app.component.html content with

```
<div style="width: 500px; height: 500px; background: yellow;">
	<as-split direction="horizontal">
		<as-split-area size="40">
			<iframe width="100%" height="100%"></iframe>
		</as-split-area>
		<as-split-area size="60">
		</as-split-area>
	</as-split>
</div>
```

Dragging the gutter to left side fast and it will lose the **onmouseup** or **drag-end** event. After that angular-split will keeping the dragging status.

**Comment by bertrandg** [comment]
Hi @Mike-Jia 
Check this demo to solve that:
https://bertrandg.github.io/angular-split/#/examples/iframes
https://github.com/bertrandg/angular-split/blob/master/src_app/app/component/examples/iframe.route.component.ts

**Comment by Mike-Jia** [comment]
Hi @bertrandg 
  Thanks for your solution, it's work now.
