### ISSUE TITLE
Not working with CDKDragandDrop?

### ISSUE THREAD

**Issue by malebolgia** [bertrandg/angular-split#182]
Is it possible to drag-and-drop an element to another pane?

https://stackblitz.com/edit/angular-split-cdk-dragandrop-test 

Thanks.

**Comment by bertrandg** [comment]
Hi @malebolgia, 
check this working example:
https://stackblitz.com/edit/angular-split-cdk-dragandrop-test-kzqpgh?file=src/app/app.component.html

I removed `*ngIf` on `<as-split-area>`, it seems to failed cdkDnD initialization..

**Comment by malebolgia** [comment]
@bertrandg 

Working perfectly. Thanks for fast response!
