### ISSUE TITLE
Gutter behavior in Firefox 67.0.4 (latest)

### ISSUE THREAD

**Issue by garyw90** [bertrandg/angular-split#183]
Accidentally clicked the wrong button closed the previous issue

There seems to be some strange behavior with the gutter (and one of the panes) in Firefox 67.0.4 (latest). I am using angular-split 3.0.2 (latest). This works fine in IE 11 and Chrome.

Attached in a zip file that demonstrates the problem. To see the issue, click on the icon on the left navigation bar for 'Users'. Then click the first user ('John Doe'), notice the gutter appears. Click the second user ('Sue Smith') and notice the gutter disappears. This appears to be related to the scroll bar on the right pane, as observed in our full application. Note this works properly in Chrome and IE 11 (our company is slow).

Also strange, if you select the second user ('Sue Smith'), then right click in the left pane (the list of users) and select Inspect Element, the gutter appears.
[split.zip](https://github.com/bertrandg/angular-split/files/3373627/split.zip)

**Comment by garyw90** [comment]
Any update on this?

**Comment by beeman** [comment]
@garyw90 can you please create a repro on StackBlitz based on [this one](https://stackblitz.com/edit/angular-split-demo)?
