### ISSUE TITLE
Nested custom gutter styling

### ISSUE THREAD

**Issue by bathams** [bertrandg/angular-split#184]
Hello, this component is such a time saver, thank you for it.

 I cannot seem to get custom gutter styling for nested splits.

Here is my stackblitz,
https://stackblitz.com/edit/angular-rc2cuu?file=angular.json

Please help.

Thanks,
Shailendra

**Comment by bertrandg** [comment]
Did you see the example?
https://bertrandg.github.io/angular-split/#/examples/custom-gutter-style
https://github.com/bertrandg/angular-split/blob/master/src_app/app/component/examples/customGutterStyle.route.component.ts

**Comment by bathams** [comment]
Yes I created a stackblitz from  your sample
https://stackblitz.com/edit/angular-iecn13

it only works for the Top and Bottom split, not for the nested split, please run the stack and you will see that the Left, Top Middle, Bottom Middle and Right are not working as expected, perhaps I am missing something.

Thanks for looking into it.

**Comment by bertrandg** [comment]
Ok just found the issue:
https://stackblitz.com/edit/angular-jhixse?file=src/app/app.component.scss

You had 2 css selectors too permissive and it affects unwanted children, check `app.component.scss` lines 30 & 37:
```
&.as-horizontal {
  ::ng-deep > .as-split-gutter > .as-split-gutter-icon {
    width: 17px !important;
    left: -8px;
    right: 8px;
  }
}
&.as-vertical {
  ::ng-deep > .as-split-gutter > .as-split-gutter-icon {
    height: 17px !important;
    top: -8px;
    bottom: 8px;
  }
}
```

**Comment by bathams** [comment]
Thank you, this works now.
