### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by smlombardi** [bertrandg/angular-split#185]
**Describe the bug**
Create simple example, the 2 areas show but no styles, no "splitter" (re-sizer) appears.

Unless I am missing something about setup, this doesn't work at all for me.

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
https://stackblitz.com/edit/angular-vaezaj-splitter

**Comment by seabass223** [comment]
adding to this in-case it is the same issue
straight out of the box, with angular 8.1.0 and using the supplied [demo code](https://stackblitz.com/edit/angular-rcqyv1?file=src%2Fapp%2Fapp.component.html)

I get 
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[SplitAreaDirective -> SplitComponent]: 
  StaticInjectorError(Platform: core)[SplitAreaDirective -> SplitComponent]: 
    NullInjectorError: No provider for SplitComponent!

**Comment by intotecho** [comment]
Add the providers line as below and it works.

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  providers: [SplitComponent]
})

**Comment by smlombardi** [comment]
@intotecho My original issue was hijacked here by @seabass223.  Your solution might help him but has no bearing on the original issue filed here.
I even tried adding the provider, nothing changed.  I cannot get the splitter to show or work.  No errors, it just does not function.

**Comment by seabass223** [comment]
@smlombardi  sorry I hijacked, Steve. I got your stackblitz to work by adding a width and a height the parent divs class. 
[https://stackblitz.com/edit/angular-vaezaj-splitter-9ghqj1?file=src%2Fapp%2Fapp.component.css](https://stackblitz.com/edit/angular-vaezaj-splitter-9ghqj1?file=src%2Fapp%2Fapp.component.css)

**Comment by smlombardi** [comment]
Thanks.  I would think this should be incorporated into the component, or documented as needed to be added to user's css.

**Comment by kokosin4ik** [comment]
I've faced with the same problem, as @smlombardi , but I don't need my parent component to have specific height, as in @seabass223  example. Is there any possibility NOT to set dynamic height, if I use horizontal direction?

**Comment by AntonyGarand** [comment]
This issue comes from the `height: 100%`  property on the .as-split-gutter: 

```css
.as-horizontal > .as-split-gutter {
    flex-direction: row;
    cursor: col-resize;
    height: 100%;
}
```
Removing it with the style editor fixes the problem in this case, although I'm not sure if there are side effects from this change.

I'll see if I can dig and fix this for hacktoberfest!

**Comment by beeman** [comment]
Closing this issue as it's not reproducible, the library works as can be seen [here](https://stackblitz.com/edit/angular-split-demo). 

Happy to accept PR's that improve the documentation.
