### ISSUE TITLE
CSS code [flex: 0 1 0] is not recognized by IE11. [flex: 0 1 0px] works on all browsers

### ISSUE THREAD

**Issue by jmesa-sistel** [bertrandg/angular-split#188]
**Describe the bug**
My problem is in IE11, the problematic line is:
[flex: 0 1 0](https://github.com/bertrandg/angular-split/blob/master/projects/angular-split/src/lib/component/split.component.scss#L36)
IE11 do not recognize `flex: 0 1 0`.

PS:
After more investigation I've found that:
`flex: 0 1 0px` 
works in all browsers

**Comment by jmesa-sistel** [comment]
@bertrandg do you continue maintaining this library?

**Comment by krzysiekkogut** [comment]
I also encountered this issue. I created a PR #190 fixing the issue.

**Comment by beeman** [comment]
Hi @jmesa-sistel, thanks for creating this issue. A fix has landed in the main branch and should be released soon.
