### ISSUE TITLE
Dropping Angular 7 support is not "patch" level update

### ISSUE THREAD

**Issue by rubiesonthesky** [bertrandg/angular-split#189]
Patch level fixes should be backward compatible. Dropping support for Angular 7 is not backward compatible in my opinion. While I understand it feels weird to make major release when the only thing that changed is dependency version change, I think it is better than doing patch release which looks like nothing major was changed. 

If nothing else was changed, library could keep Angular 7 support until next release that have some other things also.

**Comment by bertrandg** [comment]
That's true, will do better next time.
