### ISSUE TITLE
Documentation: Order Input is missing from Split-Area directive

### ISSUE THREAD

**Issue by vlodko** [bertrandg/angular-split#191]
**Describe the bug**
Please specify library version.

**To Reproduce**
Go to [https://bertrandg.github.io/angular-split/#/documentation](https://bertrandg.github.io/angular-split/#/documentation)

Try to find Order input for Split area directive - it is missing.
However, the directive class contains it.

**Comment by beeman** [comment]
Hi @vlodko, thanks for creating this issue. It's fixed in #245 and will be online when v4 of this library is published.

**Comment by vlodko** [comment]
yay, thanks @beeman
