### ISSUE TITLE
Showing/Hiding messes up order

### ISSUE THREAD

**Issue by sbradl** [bertrandg/angular-split#206]
When hiding and reshowing a split-area it gets appended to the end instead of showing it at it's initial position. This is because the css-order attribute is set incorrectly.

https://stackblitz.com/edit/angular-q1igtp

**Comment by dck5132** [comment]
@sbradl - if you add an [order] property to each of the as-split-area elements and assign them in the order you want them to be shown it will work as expected

Example - https://stackblitz.com/edit/angular-ua1jt5?file=src/app/app.component.html

**Comment by sbradl** [comment]
Thanks @dck5132 

This should be added to the documentation.

**Comment by beeman** [comment]
This is fixed in #245, the site will be updated when the new version is released.
