### ISSUE TITLE
On the examples page, from Roll/unroll on, I get console errors saying "Cannot read property 'direction' of undefined", and the page is broken.

### ISSUE THREAD

**Issue by kuehlc** [bertrandg/angular-split#208]
**Describe the bug**
Please specify library version.

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
https://stackblitz.com/

**Comment by kuehlc** [comment]
Same thing for 'guttersize' undefined in the console.

**Comment by BertrandMarechal** [comment]
I had a look and everything seems fine on Chrome 79

**Comment by kuehlc** [comment]
That's good. Not sure what caused the issue. I was on chrome on my work computer in an incognito tab at the time when it happened.

**Comment by kuehlc** [comment]
I was on the roll/unroll example. I clicked each button. I then clicked on the examples dropdown and clicked on the next example. This is what showed on the page and what my console said. Maybe it has to do with switching between examples after using the buttons on the previous one?
I should clarify that roll/unroll example worked, which I think may support my theory of the switching between examples.
After looking into it more. I can't get the access and interact page to work at all. I've tried completely reloading, hard reloading, opening in incognito, and different browser. Nothing works.
![split-error](https://user-images.githubusercontent.com/22896763/73456641-dbe98d00-4337-11ea-94a2-890f7ce8fea1.PNG)

**Comment by bertrandg** [comment]
Weird, will take a look..

**Comment by kuehlc** [comment]
Any word on this?

**Comment by beeman** [comment]
@kuehlc the issue was that the demo page tried to access `splitEl` before it was initialized.

Fixed in #247 by using the null-conditional operator, released in `angular-split@4.0.0-beta.1`.

Demo page will be updated when v4 gets released.
