### ISSUE TITLE
Map info window does not come out of the split pane

### ISSUE THREAD

**Issue by aswathy29592** [bertrandg/angular-split#209]
Hi
I have loaded agm- Angular google map in one of the split pane. On hover on each marker of the map, an info window is shown on the marker. This window is not currently popping out of the split pane. Instead it sits within the pane which makes the map move to show the info window fully. Is it possible to bring the window out of the pane so that it is on top of the other panes popped out ?

**Comment by beeman** [comment]
@aswathy29592 can you please provide a StackBlitz repro?

You can work off of this example: https://stackblitz.com/fork/angular-split-demo
