### ISSUE TITLE
Emit event when all panels are built (layout ready)

### ISSUE THREAD

**Issue by rustygreen** [bertrandg/angular-split#210]
# Issue
Thanks for the great component. I have an issue where I have child components within a set of dynamically built as-split-areas and I need to know the width and height of the available space for each component in the split area. However, the angular-split component does not seem to provide any event/hook into when the entire layout is done and the width/height are final. What I am seeing now is various sizes while the split component is "building" and no way to know when it is "complete".

# Feature Request
I would like to request an output for when the entire as-split component has completed building the panels.

**Example:**
NOTE: `buildEnd` is fired when all split areas are completed (size is final).
```html
<as-split (buildEnd)="buildEnd($event)">
  <as-split-area size="50">Left</as-split-area size>
  <as-split-area size="50">Right</as-split-area size>
</as-split>
```

**Another example:**

```html
<as-split (buildEnd)="buildEnd($event)">
  <as-split-area size="50">
     <my-other-component></my-other-component>
  </as-split-area size>
  <as-split-area size="50">Right</as-split-area size>
</as-split>
```

```javascript
class MyOtherComponent {
  ngOnViewInit() {
    // NEED TO KNOW AVAILABLE WIDTH/HEIGHT HERE
   // Currently if I grab the available space it is unreliable because the as-split-area is sometimes still in the process of building and does not have the final available space calculated yet.
  }
}
```

**Comment by bertrandg** [comment]
Hi,
Did you try to do your calcul stuff in your main component `ngAfterViewInit()` hook?
It should be correct there..
