### ISSUE TITLE
Does it work without setting the height of the containing div?

### ISSUE THREAD

**Issue by smartm0use** [bertrandg/angular-split#211]
**Describe the bug**
It doesn't work if I don't set a fixed height to the containing div. I can't see the gutter and splitting doesn't work.

**To Reproduce**
https://stackblitz.com/edit/angular-rcqyv1
Just remove `height: 500px;` from app.component.html to reproduce it.

**Comment by smartm0use** [comment]
Any comment about this?

**Comment by dck5132** [comment]
This needs the parent element to have a defined height.

The closed issue here explains it in more detail <https://github.com/bertrandg/angular-split/issues/65>

**Comment by bertrandg** [comment]
No sorry, it can't works without specifying an height.
