### ISSUE TITLE
How to scroll a split area on main window scrolling?

### ISSUE THREAD

**Issue by smartm0use** [bertrandg/angular-split#215]
Hello, I have the following situation:

https://angular-atwlce.stackblitz.io

There is any way or any library option to scroll the right panel when users scroll the main windows?
As you can see in my example I have 3 scrollbars. I would like to have 2 vertical scrollbars, one for left panel and one on the right to scroll the main window and the right panel.

How to reach that?

**Comment by bertrandg** [comment]
Sorry you can't do that currently and that's out of library's scope.

**Comment by bertrandg** [comment]
Or maybe, if i understand well what you want, you have to avoid scrollbar in your right area, so it will scroll on full page on this zone..
