### ISSUE TITLE
Missing support for Angular 9

### ISSUE THREAD

**Issue by arobinson** [bertrandg/angular-split#218]
**Describe the bug**
```
npm WARN angular-split@3.0.2 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-split@3.0.2 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**
Install angular-split into an Angular 9 working-copy and run `npm install`

**Comment by tosehee** [comment]
bump

**Comment by bertrandg** [comment]
Yes, will do it this week!

**Comment by bertrandg** [comment]
I've just published version `3.0.3`.

**Comment by tosehee** [comment]
Thanks for quick turnaround!

**Comment by robinNode** [comment]
> I've just published version `3.0.3`.

angular 9 is supported now?

**Comment by Mysame** [comment]
@bertrandg Thank you very much for the quick update.
However, it's advisable to also approve pull request https://github.com/bertrandg/angular-split/pull/204 for Ivy compatibility.

**Comment by FranPn** [comment]
I installed the latest version of Angular 9 (9.0.1) and installed the latest version of angular-split (v. 3.0.3).
I created a simple split vertical but it doesn't work. How should I behave?

Use Chrome 80.0.3987.122

**Comment by kottartillsalu** [comment]
Has anyone been able to make it work with Angular 9?

**Comment by natilivni** [comment]
bump

**Comment by dck5132** [comment]
If you add:  schemas: [CUSTOM_ELEMENTS_SCHEMA] to you app module inside the @NgModule decorator it should fix the issue for your build @kottartillsalu

**Comment by bryantlikes** [comment]
Working for me with Angular 9. I had to change the import to use the .forRoot() unlike what is shown in the examples. Also had to do a fresh ng build so that the cli would compile the module es2015 as esm2015.

**Comment by siva5176** [comment]
Facing a issue with Angular 9,
error NG8001: 'as-split-area' is not a known element:
    1. If 'as-split-area' is an Angular component, then verify that it is part of this module.
    2. If 'as-split-area' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

AnyOne able to fix it?

**Comment by dck5132** [comment]
@siva5176 have you tried adding `schemas: [CUSTOM_ELEMENTS_SCHEMA]` to your app module inside the @NgModule decorator?

**Comment by siva5176** [comment]
> @siva5176 have you tried adding `schemas: [CUSTOM_ELEMENTS_SCHEMA]` to your app module inside the @NgModule decorator?

Thanks for your response, I tried but still no use, same error

**Comment by beeman** [comment]
Because the maintainer of `angular-split` clearly lost interest in maintaining it, and does seem to be interested in adding collaborators, I decided to fork this awesome library.

The fork is called `ngx-split`. Check the [homepage](https://beeman.github.io/ngx-split/), [npm package](https://npm.im/ngx-split/) and [repo](https://github.com/beeman/ngx-split/) . 

Feel free to submit PR's and I'll consider merging them! 🙏

**Comment by beeman** [comment]
@arobinson Thanks to @bertrandg I've been given permissions to maintain this library. I just released a new beta, can you verify if this works with Angular 9?

**Comment by beeman** [comment]
Support for Angular 9 is now verified using [this repo](https://github.com/beeman/split-sandbox-v9).

If you find any issues with v9, please open a new issue with a reproduction. 🙏
