### ISSUE TITLE
IE10 support

### ISSUE THREAD

**Issue by uladzimir-miadzinski** [bertrandg/angular-split#219]
**Describe the bug**
"angular-split": "3.0.2"
Hi, I want to ask if it has ie10 support? Or the thing that package is not working  in IE10 is not a bug because you don't support it?

**To Reproduce**
https://bertrandg.github.io/angular-split/#/examples/simple-split
simple split example didn't work. No errors in console, it seems that some styles that you use are not supported in ie10. Did you investigated it?

I checked generated css for browser support, it seems that problem is in 'flex' property
![image](https://user-images.githubusercontent.com/8378842/74636772-beab2000-5179-11ea-9576-926721ee0fb0.png)

Also I found that flex in IE10 doesn't support calc() https://github.com/philipwalton/flexbugs#flexbug-8

**Comment by Mysame** [comment]
I doubt IE10 is supported, flex / calc() simply don't work there, and this library is based around those properties.
Also, since IE10 is now official end-of-life since 2020/01/14, I see no reason why this package should support it.

**Comment by uladzimir-miadzinski** [comment]
a lot of apps still work with windows7/ie10, not every company has posibilities to migrate on win10/edge, if fix is possible (use width property) maybe it may take its place to increase browser compability

**Comment by beeman** [comment]
Hey @uladzimir-miadzinski, thanks for creating this issue. 

I've merged #190 and it's available to test on `angular-split@4.0.0-beta.0`. Could you check if this fixes the issue?

I don't plan on actively working on supporting any EOL browsers myself, but if it can be supported with small, non-intrusive patches (like in #190) I will consider merging any PR's.

So, closing this issue for now, I'm open to consider small patches that improve the experience.
