### ISSUE TITLE
Angular 4.0 support?

### ISSUE THREAD

**Issue by xwb1989** [bertrandg/angular-split#22]
Hi,

Wondering whether there is a plan to support Angular 4.0? 

I just to compile against Angular 4.0 with angular-cli@1.0.0, got errors like:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ${MY_APP_PATH}/node_modules/angular-split/node_modules/@angular/core/src/metadata/ng_module.d.ts
```

**Comment by bertrandg** [comment]
hi,
Yes sure, I will take a look this week and publish a compatible version. ;)

**Comment by bertrandg** [comment]
Good news @xwb1989, 
I reproduce your error using CLI 1.0.0 / angular 4.0.0 and it works just by upgrading to angular 4.0.1!
Seems they made a fix to support old compiled template libraries.

Let me know if it work for you.

**Comment by xwb1989** [comment]
Hi @bertrandg , thank you for the notice. I just tried 4.0.1 with a clean `npm install`, looks like it's still failing with the same error. Could you please double check?

**Comment by bertrandg** [comment]
yes you're right, I spoke a bit quick, it always fail after first build after `ng serve` but not when next changes..

Anyway, I'm currently regenerating the lib with 4.0 and will publish it quickly! ;)

**Comment by bertrandg** [comment]
I've just published `0.2.0` on npm, should work now!

**Comment by xwb1989** [comment]
It works! Thank you!

**Comment by GuyShaanan** [comment]
Should this be re-opened?

angular: 4.0.1,
angular-split: ^0.2.0
angular-cli: 1.0.0.

When running with `ng serve` the following error is shown in browser:

```
Error:
Unhandled Promise rejection: Template parse errors:
'split-area' is not a known element:
1. If 'split-area' is an Angular component, then verify that it is part of this module.
2. If 'split-area' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message....
```

Of course I've imported the module (and the same code works in Plunker with SystemJS):
```
@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        AppRoutingModule,
        AngularSplitModule, // <-------
        BrowserAnimationsModule,
        NgbModule.forRoot(),
    ],
    bootstrap: [
        AppComponent
    ]
})
export class AppModule {
}
```

Thanks (and this is an awesome library!)

**Comment by bertrandg** [comment]
That's weird..
I've just test to create a new project using `@angular/cli 1.0.0` and `@angular/* 4.0.1`.
Then I added `angular-split 0.2.0` with:
```
<div style="width: 500px; height: 500px; background-color: red;">
    <split>
      <split-area>
          AAAAA
      </split-area>
      <split-area>
          BBBB
      </split-area>
    </split>
</div>
```

I lunched it with `ng serve` and it works well.
Try to remove your `node_modules`, then make `npm cache clean` and `npm i`
