### ISSUE TITLE
Setting direction attribute value dynamically from directive

### ISSUE THREAD

**Issue by Rajpradeep26** [bertrandg/angular-split#228]
**I would like to switch between split directions based on window screen size**
Initially i have the split direction as 'horizontal', but when window is resized below 768px, i have to switch the split direction to 'vertical' based on responsiveness.

**Get the direction attribute value from a custom directive**
I would like to add a custom directive which has to dynamically set the direction value. Here is the sample mockup i tried https://stackblitz.com/edit/angular-gta2ne?file=src%2Fapp%2Fapp.component.html

But this did not help me. Could you please assist me further? Thanks

**Comment by vishalsingh119** [comment]
I am also trying to achieve a similar thing but facing the issue-
on the Click toggle button want to change the direction of split but vertical direction split not working.
[direction]="splitterDirection  ? 'horizontal' : 'vertical'"

Any Idea?

**Comment by nomeaning777** [comment]
@Rajpradeep26 
There are two issues your code.

 1. The direction is updated only once because `onWindowResize` doesn't update it..
 2. `@HostBinding('attr.direction')` updates only DOM attribute not component input.

Working example: https://stackblitz.com/edit/angular-3ht2p9
Thanks.

**Comment by beeman** [comment]
Looks like @nomeaning777 provided a fix, thanks for that!

Closing this issue, feel free to ping me if it's an actual issue in the library and we can reopen it.
