### ISSUE TITLE
ERROR in node_modules/angular-split/lib/module.d.ts:4:25 - error TS1149

### ISSUE THREAD

**Issue by shankarvn** [bertrandg/angular-split#229]
**Describe the bug**
Please specify library version.

Running into compilation issues with angular-split on Angular9 - 

ERROR in node_modules/angular-split/lib/module.d.ts:4:25 - error TS1149: File name '<project>/node_modules/angular-split/lib/directive/splitarea.directive.d.ts' differs from already included file name '<project>/node_modules/angular-split/lib/directive/splitArea.directive.d.ts' only in casing.

import * as ɵngcc2 from './directive/splitarea.directive';

It does look like the report is legitimate. The file name is indeed splitArea.directive.d.ts with a capital A while the reference in the module is all lower case. 

I have tried this in my tsconfig.json - "forceConsistentCasingInFileNames": false, but it is not helping looks like.

Version used

"angular-split": "3.0.3",

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
https://stackblitz.com/

Unable to demonstrate the compilation issue on stackblitz.

**Comment by beeman** [comment]
@shankarvn I released a new beta `angular-split@4.0.0-beta.0`, can you please verify if that still has the issue? 

If so, please provide a repro so we can reopen the issue and look at fixing it.
