### ISSUE TITLE
angular-split not working with webpack

### ISSUE THREAD

**Issue by kejtizuki** [bertrandg/angular-split#23]
Hello, 

In our angular2 application we use webpack. I'm trying to install angular-split. In my app.module I imported AngularSplitModule and added it to imports in the same way as in your examples. I get the following error in the console: 
"Unexpected value 'AngularSplitModule' imported by the module 'AppModule"

My package json dependencies looks like that: 

"dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/router": "3.4.4",
    "@google-cloud/speech": "0.6.0",
    "angular-in-memory-web-api": "0.3.1",
    "angular-modal-gallery": "^2.0.2",
    "angular-split": "^0.2.0",
    "angular2-modal": "^2.0.3",
    "angular2-moment": "^1.3.3",
    "animate.css": "3.5.1",
    "app-module-path": "1.1.0",
    "async": "2.1.4",
    "awesome-typescript-loader": "3.0.0-beta.9",
    "bcrypt-nodejs": "0.0.3",
    "bluemix-objectstorage": "0.1.2",
    "body-parser": "1.16.0",
    "bootstrap": "4.0.0-alpha.4",
    "bootstrap-loader": "2.0.0-beta.20",
    "bpmn-js": "^0.19.0",
    "browser-sync": "2.18.6",
    "cfenv": "1.0.3",
    "chalk": "1.1.3",
    "collections": "5.0.6",
    "compression": "1.6.2",
    "config": "1.24.0",
    "connect-multiparty": "2.0.0",
    "cookie-session": "1.2.0",
    "core-js": "2.4.1",
    "csurf": "1.9.0",
    "csvtojson": "1.1.2",
    "curlrequest": "1.0.1",
    "debug": "2.6.0",
    "decompress": "4.0.0",
    "dotenv": "2.0.0",
    "ejs": "2.5.5",
    "errorhandler": "1.5.0",
    "express": "4.14.0",
    "express-flash": "0.0.2",
    "express-session": "1.15.0",
    "express-status-monitor": "0.1.9",
    "express-validator": "2.21.0",
    "fluent-ffmpeg": "2.1.0",
    "font-awesome": "4.7.0",
    "font-awesome-sass-loader": "1.0.3",
    "fs": "0.0.1-security",
    "generate-function": "2.0.0",
    "generate-object-property": "1.2.0",
    "gspeech-api": "1.0.0",
    "httpolyglot": "0.1.2",
    "ionicons": "^2.0.1",
    "jimp": "0.2.27",
    "jquery": "2.2.4",
    "jquery-slimscroll": "1.3.8",
    "json-loader": "0.5.4",
    "json-server": "^0.9.5",
    "jsonpointer": "4.0.1",
    "lodash": "4.15.0",
    "lusca": "^1.4.1",
    "method-override": "2.x",
    "moment": "2.17.1",
    "morgan": "1.7.0",
    "multer": "1.2.0",
    "natural": "0.4.0",
    "ng2-bootstrap": "1.1.16",
    "ng2-ckeditor": "1.0.7",
    "ng2-dnd": "^2.2.2",
    "ng2-smart-table": "0.5.0",
    "ng2-tree": "0.0.2-7",
    "ng2-uploader": "1.1.0",
    "node-sass-middleware": "0.9.8",
    "normalize.css": "5.0.0",
    "npm": "4.1.2",
    "passport": "0.3.2",
    "passport-ibmid-oauth2": "0.0.8",
    "passport-idaas-openidconnect": "2.0.1",
    "passport-local": "^1.0.0",
    "pg": "6.1.0",
    "pg-connection-string": "0.1.3",
    "pg-hstore": "2.3.2",
    "postcss-load-config": "1.0.0",
    "postcss-loader": "1.0.0",
    "postcss-ordered-values": "2.2.3",
    "pug": "2.0.0-beta8",
    "randomstring": "1.1.5",
    "reflect-metadata": "0.1.9",
    "request": "2.79.0",
    "resolve-url-loader": "1.6.1",
    "rimraf": "2.6.1",
    "rmdir": "1.2.0",
    "rxjs": "5.0.1",
    "search-index": "^0.9.15",
    "sequelize": "3.30.0",
    "sequelize-mock": "0.6.1",
    "serve-static": "1.11.2",
    "should": "10.0.0",
    "socket.io": "1.7.2",
    "socket.io-client": "1.7.2",
    "unzip": "0.1.11",
    "vaadin-split-layout": "^1.1.0",
    "watson-developer-cloud": "2.15.2",
    "webpack": "2.2.1",
    "winston": "2.3.0",
    "winston-daily-rotate-file": "1.4.3",
    "xls-to-json": "0.4.0",
    "xml-js": "0.9.7",
    "xml2js": "0.4.17",
    "xtend": "^4.0.1",
    "zone.js": "0.7.7"
  },
  "devDependencies": {
    "pre-push": "0.1.1",
    "precommit-hook": "3.0.0",
    "js-beautify": "1.6.8",
    "@types/jasmine": "2.5.35",
    "@types/jquery ": "2.0.33",
    "@types/jquery.slimscroll": "1.3.30",
    "@types/lodash": "0.0.28",
    "@types/node": "6.0.46",
    "@types/source-map": "0.1.27",
    "@types/uglify-js": "2.0.27",
    "@types/webpack": "2.0.0",
    "angular2-router-loader": "0.3.4",
    "angular2-template-loader": "0.6.0",
    "awesome-typescript-loader": "3.0.0-beta.9",
    "babel-core": "6.22.1",
    "babel-loader": "6.2.10",
    "canonical-path": "0.0.2",
    "chai": "3.5.0",
    "concurrently": "3.1.0",
    "copy-webpack-plugin": "3.0.1",
    "css-loader": "0.26.1",
    "exports-loader": "0.6.3",
    "extract-text-webpack-plugin": "2.0.0-rc.3",
    "file-loader": "0.9.0",
    "git-hooks-win": "1.1.11",
    "hjson": "2.4.1",
    "html-loader": "0.4.3",
    "html-webpack-plugin": "2.15.0",
    "html-webpack-pug-plugin": "0.0.3",
    "http-server": "0.9.0",
    "imports-loader": "0.6.5",
    "istanbul": "0.4.2",
    "jasmine-core": "2.4.1",
    "jshint": "2.9.4",
    "karma": "1.2.0",
    "karma-jasmine": "1.0.2",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "1.8.0",
    "lite-server": "2.2.2",
    "mocha": "3.0.0",
    "node-sass": "4.0.0",
    "null-loader": "0.1.1",
    "phantomjs-prebuilt": "2.1.7",
    "pug-html-loader": "1.0.9",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "1.6.1",
    "sass-loader": "6.0.2",
    "should": "10.0.0",
    "style-loader": "0.13.1",
    "supertest": "^2.0.0",
    "tslint": "^3.15.1",
    "typescript": "2.1.6",
    "url-loader": "0.5.7",
    "webdriver-manager": "10.2.5",
    "webpack": "2.2.1",
    "webpack-dev-server": "1.16.2",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "0.14.0",
    "webpack-node-externals": "1.5.4"
  },

I would be very grateful if you could help.

**Comment by bertrandg** [comment]
hi @kejtizuki,
Wow your package.json is huge! :)

I see that you are using angular-split `0.2.0` with angular `2.4.4`.

You should use `0.1.20` for angular `<4.0.0`
and `0.2.0` for angular `>4.0.0`

But your error doesn't seems related to that..
Are you using angular-cli?

**Comment by kejtizuki** [comment]
Thanks for your answer.  I'm not using angular-cli. Actually I changed the version of angular-split and now its working fine. Thank you for help!

**Comment by bertrandg** [comment]
Cool

**Comment by samidabeast** [comment]
@bertrandg Can you put this in the documentation with the npm install information? I just ran into this issue and the version specification fixed it as well.
