### ISSUE TITLE
Setting gutter hover style

### ISSUE THREAD

**Issue by batham** [bertrandg/angular-split#231]
Hello,

As per this sample https://stackblitz.com/edit/angular-jhixse?file=src/app/app.component.scss

I want to define the style global instead of using :host or ::ng-deep.

Do you recommend an easy way I can have these styles global.

I have over 20 components which utilize this great tool and in each component I have these styles defined.

I would like to move this into a global scss.

Thank you for your help.
Shailendra

**Comment by beeman** [comment]
@batham I've forked this library as this no longer seems to be maintained.

One of the things I like to do is get the styles out of the main library and offer a separate .scss files, so the user can decide which flavor they want. Would that work for your use case?

Curious to hear what you think, feel free to join the party: https://github.com/beeman/ngx-split/issues/4

**Comment by batham** [comment]
@beeman I was not aware this excellent library is not maintained.

Glad to hear you have forked and willing to do the change.

The idea of a separate file is a great idea, this will reduce my .scss files for all components.

Have a main .scss file and users can override these styles in their component if they want it.

**Comment by beeman** [comment]
Closing this issue, this will be part of #248
