### ISSUE TITLE
MinSize MaxSize dont work on vertical direction

### ISSUE THREAD

**Issue by arturorv00** [bertrandg/angular-split#236]
Hi,

I am trying to set a minSize for a vertical direction split area, but it does not. 

does it work at all for vertical mode?

Refer to the following example:

[https://stackblitz.com/edit/angular-dhzydt](https://stackblitz.com/edit/angular-dhzydt)

`<as-split direction="vertical" unit="percent">
		<as-split-area size="25" minSize="20">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tiam, quis nostrud exercitation
				ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
				voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
		</as-split-area>
		<as-split-area size="75" minSize="20">
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam
				rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
				explicabo. </p>
		</as-split-area>
	</as-split>`

**Comment by nomeaning777** [comment]
Your code uses version 2 but `minSize` and `maxSize` are introduced in version 3.
it seems that it works as expected in version 3. https://stackblitz.com/edit/angular-zvqrzg

**Comment by arturorv00** [comment]
ohhhh my bad. Thanks!
