### ISSUE TITLE
 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by AliWieckowicz** [bertrandg/angular-split#25]
When I follow you instructions for webpack builds I get the following error.  I'm at a loss for a solution and so have to ask for help.  Any thoughts?

./~/angular-split/~/@angular/core/@angular/core.es5.js
5870:15-36 Critical dependency: the request of a dependency is an expression
./~/angular-split/~/@angular/core/@angular/core.es5.js
5886:15-102 Critical dependency: the request of a dependency is an expression

**Comment by bertrandg** [comment]
Hi @AliWieckowicz ,
sorry I've no idea where it comes from..

But be sure to use angular-split `0.1.20` for angular `<4.0.0`
and angular-split `0.2.0` for angular `>=4.0.0`

**Comment by bertrandg** [comment]
Try latest 1.0.0 and reopen if still there.
