### ISSUE TITLE
angular-split with ngFor

### ISSUE THREAD

**Issue by kejtizuki** [bertrandg/angular-split#26]
In my application I have a list of objects which is an @Input(). Two components share this list. In one of them I'm modifying the list (adding / deleting elements) and in the second one I'm displaying the list in the following way: 
```
<split-area *ngFor="let item of items">
    {{item.name}}
</split-area>
```
When I add a new element to this list by using splice method (for instance I add a new element on 2nd position) the new element is displayed at the end of the list (instead of 2nd position).
I've checked if it works when I use *ngFor on a <div> tag and in this case it's displayed in the proper position, so I assume that there is something wrong with <split-area>. 
Any ideas how to change this behavior? 

Thanks in advance! :)

**Comment by bertrandg** [comment]
Yes seems to be normal behavior, last DOM node added at the end if no position provided.

Try using this:
```js
<split-area *ngFor="let item of items; let i = index" [order]="i">
    {{item.name}}
</split-area>
```

**Comment by kejtizuki** [comment]
You're right, it works now. Thank you :)
