### ISSUE TITLE
Disable split-gutter

### ISSUE THREAD

**Issue by kejtizuki** [bertrandg/angular-split#27]
Is there any way to disable split-gutter and than enable it again? I mean the same behavior as for example button has.

**Comment by kejtizuki** [comment]
I have probably explained in the wrong way what I mean. I found on your website that it's possible to disable all split gutters within split tag. I have created the split panel with for loop. There are 5 split-gutters generated and what I need is to disable only one of them by using a boolean value from the item object. 
The code looks like that:

```
<split direction="horizontal" [gutterSize]="4">
          <split-area *ngFor="let item of items; let i = index" [size]="item.width" [order]="i">
              {{item.name}}
          </split-area>
      </split>
```

I would be very grateful for help :)

**Comment by bertrandg** [comment]
hi @kejtizuki,
Sorry, there's currently no way to disable only one specific gutter, only none or all activated..

**Comment by kejtizuki** [comment]
I see. Thanks :)
