### ISSUE TITLE
Is there existing an non angular-cli example?

### ISSUE THREAD

**Issue by namnguyendev** [bertrandg/angular-split#29]
I did as your mention at https://bertrandg.github.io/angular-split/#/ and also check at https://plnkr.co/edit/tEjcXo?p=preview but not successfuly.
Do you have an example with angular quickstart, which is non cli?
Thank for your support.

**Comment by bertrandg** [comment]
Hi
Sorry but, except my plunker example using systemjs, I've not experiment a lot without using angular cli (which I think is currently the best way to use ng2).

Please provide more info/example about what's wrong.

**Comment by namnguyendev** [comment]
Hi Bertrandg,
Thank you very much, i found the answer at #2 by giving height to parent it get solved.
Could you please note at README for the new user can getting it work?

**Comment by namnguyendev** [comment]
Another things, could you please share hints how to generate <split> dynamically?
Is it posible? I'm a new JS!
Thanks!

**Comment by bertrandg** [comment]
Check angular-split website sources, you will fond examples:
https://github.com/bertrandg/angular-split/tree/website-src
