### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by KelvinKaYiuLok** [bertrandg/angular-split#33]
Is Horizontal scroll support for this control?

**Comment by HugzM** [comment]
I'm also interested in that feature. it seems like the split area directive set the overflow:x hidden with the ! important so I assume that it is mandatory but I'm would like to have an explanation also

**Comment by bertrandg** [comment]
Hi @KelvinKaYiuLok @HugzM , 
Sorry for the delay!

Yes you can have an horizontal scroll using a `div` container inside your `split-area` like the following plunker:
http://plnkr.co/edit/mOqKDF?p=preview

let me know if it helps you.

**Comment by przemyslawzamorski** [comment]
It helps  me 👍

**Comment by He-Wolf** [comment]
Hello @bertrandg ,

I checked the plunker project, and unfortunatelly it does not work any more.

I created a stackblitz project which uses div as you recommended. I do not see any horizontal scroll bar.

Stackblitz project: https://stackblitz.com/edit/angularsplit-horizontalscroll

How could I implement horizontal scrolling?

**Comment by nomeaning777** [comment]
@He-Wolf It works perfectly if you change `split-area` to `as-split-area` in `app.component.scss`

**Comment by He-Wolf** [comment]
Yes, you are right. :) I corrected the stackblitz project.
Thanks for the quick response and support!
