### ISSUE TITLE
Can't drag the gutter

### ISSUE THREAD

**Issue by chaad18** [bertrandg/angular-split#35]
Made an angular-cli project implementing a basic split. The gutter is displayed but it cannot be dragged. Is there something I'm missing?

**Comment by seanhines** [comment]
i am having this issue as well, i can't quite seem to pin it down the exact work around but it seems to work for me if i set the height of the split (i.e. <split direction="vertical" height="900">)

**Comment by bertrandg** [comment]
Yes, be sure that your `<split>` component is inside a tag with height specified, you have 2 choices:
- Set it to specific height in pixels: `height: 300px`, what I did here: https://bertrandg.github.io/angular-split/#/examples
- Set it to a percentage: `height: 100%` but in that case, you have to set all parents height too, more about this: http://stackoverflow.com/questions/5657964/css-why-doesn-t-percentage-height-work

**Comment by TheFron11** [comment]
HI Bertrandg,
I tried to implement angular-split solution.  I am getting the gutter but am unable to drag it.  When i click on it nothing happens.   I tried to adjust height as the others mentioned.  I know this issue has been closed, if you want i can open a new issue.  I also imported the module in my module.ts file.

<div style="height: 300px; width: 100%; background: #cc0000">
  <as-split direction="horizontal">
    <as-split-area size="50">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tiam </p>
    </as-split-area>
    <as-split-area size="50">
      <p>Sed ut perspiciatis unde omnis iste natus error sit </p>
    </as-split-area>
  </as-split>
</div>

**Comment by TheFron11** [comment]
`HI Bertrandg,
I tried to implement angular-split solution.  I am getting the gutter but am unable to drag it.  When i click on it nothing happens.   I tried to adjust height as the others mentioned.  I know this issue has been closed, if you want i can open a new issue.  I also imported the module in my module.ts file.

<div style="height: 300px; width: 100%; background: #cc0000">
  <as-split direction="horizontal">
    <as-split-area size="50">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tiam </p>
    </as-split-area>
    <as-split-area size="50">
      <p>Sed ut perspiciatis unde omnis iste natus error sit </p>
    </as-split-area>
  </as-split>
</div>`

**Comment by bertrandg** [comment]
Hi @TheFron11 

Your code seems good..
Give me your angular-split & angular versions.

Just created this [working stackblitz](https://stackblitz.com/edit/angular-3qy9pk?file=src%2Fapp%2Fapp.component.html) with your code..

**Comment by TheFron11** [comment]
Angular 7 and angular-split version is 2.0.0

**Comment by bertrandg** [comment]
Ok, should works..
Can't help you more, check the stackblitz, it works with your code.
Please try to reproduce your issue in a new stackblitz if you can.

**Comment by TheFron11** [comment]
comparing with your example, when i click on the gutter, classes is-dragged and is-dragging are not getting added in my code.

**Comment by jacobbutton** [comment]
@bertrandg - I'm having the same issue as @TheFron11. My implementation is 'horizontal' as well so the height declaration isn't the issue.

I'm on the latest 3.0.0-beta.5 preview and I've forked the code so I could add some console outputs to debug. As best I can tell, the event listeners on the gutters are never being added because the UndetectedEventPlugin.addEventListener is never firing. I'm not sure why that is but I thought I'd see if you have any insights on why that provider wouldn't be working. I'll keep looking and report back if I find anything new.

**Comment by bertrandg** [comment]
@jacobbutton Please provide a stackblitz demo showing your issue.

**Comment by jacobbutton** [comment]
@bertrandg - disregard previous post. I tracked the issue down.

I was not importing AngularSplitModule.forRoot() in the main module. Just AngularSplitModule in a child module. The UndetectedEventPlugin was never being loaded into the application. I should have paid closer attention to the documentation after the version update.

Everything is now working as expected.

**Comment by mowgliLab** [comment]
I was facing the same problem. No gutter and no drag possible. The answer was simply to set a height for the parent as @bertrandg said.
I think this problem could be a canditate to note in the README or in a FAQ section.

Note : Instead of using _height: 100%_ it works with _height: 100vh_

**Comment by joe20123** [comment]
The library looks very promising, only problem for me is that it only shows horizontal even though I've set 'direction' to be 'vertical'. Note that inside each as-split-area, there is a component. Not sure if anybody has ever come across this behavior...

**Comment by bertrandg** [comment]
Hi @joe20123 
I think you missed something, please provide a stackblitz to allow me help you.

**Comment by joe20123** [comment]
Hi @bertrandg,
Thanks very much for the response. The project I worked on is quite complicated, it has quite a few shared modules with a lot of layered components, also using 3rd party controls. However, I've managed to create a stackblitz to show the problem. It didn't mirror the exact structure of our code, however, it does in effect show the exact issue I am facing. 
The [direction] seems not responsive to 'vertical'...
[](https://stackblitz.com/edit/angular-ynvjem)
thanks!

**Comment by bertrandg** [comment]
You were missing specifying a height:
https://stackblitz.com/edit/angular-2jw1zn?file=src%2Fapp%2Funder-test%2Funder-test.component.html

**Comment by joe20123** [comment]
thanks@bertrandg. If I want to change the direction to 'horizontal', it would not work as expected, the splitter bar stays as vertical. 
https://stackblitz.com/edit/angular-ynvjem?file=src%2Fapp%2Funder-test%2Funder-test.component.html

**Comment by bertrandg** [comment]
Be careful how you use angular property, `<as-split [direction]="vertical">` means it will looks for a variable named `vertical` in your component class.

To use string value you have to write:
````html
<as-split [direction]="'vertical'">
````
or
````html
<as-split direction="vertical">
````

**Comment by joe20123** [comment]
thank you, awesome control.
