### ISSUE TITLE
Can't drag gutter when splitting flex item using @angular/flex-layout

### ISSUE THREAD

**Issue by racerhere** [bertrandg/angular-split#37]
Please take a look at this Plunkr: [https://plnkr.co/edit/jLMmkWGnH1etFLkBCi8b?p=preview](https://plnkr.co/edit/jLMmkWGnH1etFLkBCi8b?p=preview).

I am trying to have a persistent unsplit content (25% on left side) and trying to vertically split the remaining 75% on the right. I do not want to split the left and right side.

Any help is appreciated.

**Comment by jerrythomas** [comment]
You can nest the split and use gutterSize=0. Remember to initialize the html and body height. 
https://plnkr.co/edit/2MXK002nMgF7DKTiQoxT?p=preview

**Comment by bertrandg** [comment]
Hi @racerhere,

Sorry for the delay,
I've implemented a demo doing what you want using angular-split `1.0.0-beta.4` (which need angular 5.x) and the latest @angular/flex-layout `2.0.0-beta.10`:
https://stackblitz.com/edit/angular-w55rly?file=app%2Fapp.component.html

**Comment by racerhere** [comment]
Thanks @bertrandg! I am unable to access the Stackblitz link.

**Comment by bertrandg** [comment]
Weird, the link below should works.. No login needed to access, this is public. Maybe a company proxy?
https://stackblitz.com/edit/angular-w55rly

Try to create a new stackblitz to know if error comes from my specific example:
https://stackblitz.com/fork/angular

**Comment by racerhere** [comment]
Yes, @bertrandg It was some firewall problem on my end. Thanks for the solution!
