### ISSUE TITLE
running into a runtime error using systemjs.config.js

### ISSUE THREAD

**Issue by rezarr** [bertrandg/angular-split#39]
Just installed npm install angular-split --save. 
added the following lines 
 'angular-split': 'node_module/angular-split/dist/index.js'
,     'angular-split': {
                    main: './index.js',
                    defaultExtension: 'js'
                }

in my app.module.ts,
I added 
import { AngularSplitModule } from 'angular-split';

@NgModule({
    imports: [
        BrowserModule
        , HttpModule
        , FormsModule
        , SelectModule
        , ReactiveFormsModule
        , AngularSplitModule
        // , SplitPaneModule
        , DropdownTreeviewModule.forRoot()
        , AgGridModule.withComponents([])
    ],

I get the runtime error :

http://localhost:3000/node_module/angular-split/dist/index.js 404 (Not Found)

Error loading http://localhost:3000/node_module/angular-split/dist/index.js as "angular-split" from http://localhost:3000/app/app.module.js

Even though, I have the file:
$ls node_modules/angular-split/dist/index.js
node_modules/angular-split/dist/index.js

less node_modules/angular-split/dist/index.js
export { AngularSplitModule } from './angularSplit.module';
export { SplitComponent } from './split.component';
export { SplitAreaDirective } from './splitArea.directive';
export { SplitGutterDirective } from './splitGutter.directive';
//# sourceMappingURL=index.js.map

Am I doing anything wrong?

**Comment by bertrandg** [comment]
I don't see anything wrong..

Did you checked if `/node_module/angular-split/dist/index.js` i physically present on disk ?
