### ISSUE TITLE
Can't drag one pane down to 0 size

### ISSUE THREAD

**Issue by manndave** [bertrandg/angular-split#40]
I need to be able to drag the gutter so that one pane is completely hidden and the other pane takes up the whole space except for the gutter on the side where the other pane was.  There seems to be some minimum size set for the panes, though I can't figure out where that is.

Any ideas?

Thx.

**Comment by manndave** [comment]
Never mind...somehow I missed "minPercent"   :-(

**Comment by zwtokio** [comment]
Duplicate of # 52

**Comment by zwtokio** [comment]
for review the following link [https://github.com/bertrandg/angular-split/issues/52](#52)

**Comment by bertrandg** [comment]
It's now possible using coming soon 1.0.0 version (currently in beta.4) to drag gutter to area size 0.

Check this example:
https://stackblitz.com/edit/angular-qrhuve

To try it:
`npm install angular-split@1.0.0-beta.4`
