### ISSUE TITLE
Is angular-split compliant to angular@4.3.0 ?

### ISSUE THREAD

**Issue by sixrandanes** [bertrandg/angular-split#45]
Hello, 

Seem like this lib is not compatible with angular@4.3.0. With angular@4.2.5, everything works for me.

I've got the same error than #41 when I start the server.

Could you please check on your side ?

Thanks you,

**Comment by bertrandg** [comment]
Hi, 
Just tried using `angular-cli@1.2.1` + `angular@4.3.0` + `angular-split@0.2.1` and it's working fine..

Maybe @cipchk got an idea why this error appears (#41)?

**Comment by cipchk** [comment]
setps: 

+ delete `node_modules`
+ run `npm install`

fix this.

**Comment by Tumeconnais** [comment]
This solution doesn't work for me.
Angular 4.2.5, AngularSplit 0.2.2

> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/giuseppe.lapenta/workspace/ilda-frontend/node_modules/angular-split/node_modules/@angular/core/core.d.ts, resolving symbol AngularSplitModule in /home/giuseppe.lapenta/workspace/ilda-frontend/node_modules/angular-split/dist/angularSplit.module.d.ts, resolving symbol AngularSplitModule in /home/giuseppe.lapenta/workspace/ilda-frontend/node_modules/angular-split/dist/angularSplit.module.d.ts

**Comment by sixrandanes** [comment]
I only use Yarn on my project and when angular-split is resolved with angular@4.3.0, I've got the same error.

**Comment by bertrandg** [comment]
hum.. 
Please, can you try with a `angular-split@0.2.1` to test if latest changes impact it?

I dont't using `yarn` change something.
Are you both using `angular-cli`?

**Comment by sixrandanes** [comment]
Yes here is my libs used :
yarn@0.27.5, angular-cli@1.2.1, angular@4.2.5, angular-split@0.2.1 and typescript@2.3.4

In yarn.lock, i ve got :
`angular-split@0.2.1:
  version 0.2.1
  resolved https://registry.yarnpkg.com/angular-split/-/angular-split-0.2.1.tgz#a4d638149d346df607c2885838225241877934dc
  dependencies:
    @angular/common ^4.0.0
    @angular/compiler ^4.0.0
    @angular/core ^4.0.0
    @angular/platform-browser ^4.0.0
    core-js 2.4.1
    reflect-metadata ^0.1.3
    rimraf ^2.5.4
    rxjs ^5.0.2
    typescript ~2.2.0
    zone.js ^0.8.4`

When 
`   @angular/common ^4.0.0
    @angular/compiler ^4.0.0
    @angular/core ^4.0.0
    @angular/platform-browser `^4.0.0` 

is resolved with angular@4.3.4, even if my project is still in angular@4.2.5, Ive got the error.

When
`   @angular/common ^4.0.0
    @angular/compiler ^4.0.0
    @angular/core ^4.0.0
    @angular/platform-browser ^4.0.0 `

is resolved with angular@4.2.5, everythings works fine.

**Comment by shoebsd31** [comment]
I just confirmed by creating a new cli project and installing angular-split with it. 

The gutter is not visible for horizontal direction.
The one that's visible for vertical direction cannot be dragged

**Comment by shoebsd31** [comment]
@bertrandg  thanks for the clarification, i got it resolved :)

**Comment by bertrandg** [comment]
cool :+1:

**Comment by sixrandanes** [comment]
I am the owner of that issue and my problem is still not resolved for me...

**Comment by sixrandanes** [comment]
There is an issue on angular/angular-cli#5855 about this, with some comments.
Any help would be useful.

Thanks.

**Comment by sixrandanes** [comment]
OK i remove all my yarn.lock and regenerate it..Should be ok.
My bad.
