### ISSUE TITLE
Default gutterSize

### ISSUE THREAD

**Issue by Sjonnie2nd** [bertrandg/angular-split#46]
Great component! A view lines of code to install and then it works out of the box.

Here a very minor, minor, minor issue.
In horizontal mode (vertical gutter) my eyes noted a small discrepancy in the shown dots caused by the default gutterSize of 10: 3 + [2] + 1 +[2] + 2. Setting it to 9 or 11 solved it.
Would it be an idea to default it to 9 or 11?

**Comment by bertrandg** [comment]
You're totally right! :)
Thanks for pointing it.

Just updated it, will be available soon in `1.0.0-beta.7` (https://github.com/bertrandg/angular-split/commit/2c8141c958e038495d0938a152e92e9de07c39f0).
