### ISSUE TITLE
Adding RTL-Support

### ISSUE THREAD

**Issue by andelz** [bertrandg/angular-split#48]
Hi, after changing the direction of the application from `ltr` to `rtl` your component isn't working as expected. Did you consider to support RTL-direction? Would be great. Thanks.

**Comment by bertrandg** [comment]
hi, 
No, that's not planned.
You can manually change the order using `<split-area [order]="x"></split-area>` when you switch from `ltr` to `rtl`.

**Comment by bertrandg** [comment]
Just added RTL support in latest beta `1.0.0-beta.9`, 
Simply add `dir="rtl"` on `<split>` component.
