### ISSUE TITLE
Size(Height) of gutter in iphone6 is too much

### ISSUE THREAD

**Issue by sardar-nale** [bertrandg/angular-split#5]
Hey,

Is this component is responsive because if I open page in iphone6 , Size (Height) of gutter line (line which splits 2 sections and able to drag) is too much.
It should be less for small devices.
Do we need to add any css for that or it is responsive by nature.

**Comment by bertrandg** [comment]
Hi,

That's your job to set it at your convenience.

Your can do it depending on the screen resolution like this:
```js
@Component({
    selector: 'my-component',
    template:  `
        <split direction="horizontal" [gutterSize]="gutterSize">
            <split-area>
                <p>Lorem ipsum dolor sit amet...</p>
            </split-area>
            <split-area>
                <p>Sed ut perspiciatis unde omnis iste natus erro...</p>
            </split-area>
        </split>`
})
export class MyComponent {
    gutterSize: number = 10 // default value

    @HostListener('window:resize', ['$event'])
    onResize(event) {
        const w = event.target.innerWidth;

        switch(true) {
            case w < 500:  this.gutterSize = 5; break;
            case w < 800:  this.gutterSize = 6; break;
            case w < 1000: this.gutterSize = 8; break;
            default:       this.gutterSize = 10; break;
        }
    }
}
```

Or using `navigator.userAgent`..

But be careful to not shrink it too much because it will be hard to tap it with finger.

**Comment by sardar-nale** [comment]
Hey i checked it in other devices it is working fine but in iphone6 safari browser it shows big splitter gutter although i set the size of gutter to be less.
using below method ;

    setGutterSize(width:any){       
         if(width < 500){
            this.gutterSize = 5;
         }else if(width < 800){
            this.gutterSize =  6;
         }else if(width < 1000){
            this.gutterSize =  8;
         }else{
            this.gutterSize =  10;
         } 
     
    }

**Comment by bertrandg** [comment]
That's weird, do you know which resolution it is?

**Comment by sardar-nale** [comment]
I think its  414X 736 and 375x667.
Could you please check your online examples on iphone.

**Comment by bertrandg** [comment]
I don't have iphone, I've only tested on multiple android phones.
Can you send a screenshot please.

**Comment by sardar-nale** [comment]
Hey,
Have you checked this issue ?

**Comment by sardar-nale** [comment]
can we set gutter visible off  if(width < 500).

**Comment by bertrandg** [comment]
No that's not possible currently.

I don't have iphone, can you send a screenshot please.

**Comment by sardar-nale** [comment]
Hey i think its possible. I can alter the css like below:
I am using scss. 
@media (max-width: 767px) {
split-gutter
	{  
		display: none!important;
	}
}

@media (max-width : 480px) {
	split-gutter
	{  
		display: none!important;
	}
}

@media (max-width : 320px) {
	split-gutter
	{  
		display: none!important;
	}
}

**Comment by bertrandg** [comment]
Yes you can do it on your own, I was talking about library features.
But your code hide gutters if screen width under 767px...

But I'm not sure to understand what's wrong, you can't send a screenshot?
If it's a real bug on iphone/safari, I would like to fix it.

**Comment by sardar-nale** [comment]
Okay let me send it

**Comment by sardar-nale** [comment]
Hi,
Uploaded screenshots.
I have taken screenshots while scrolling down from top to bottom.
You can see in screenshot 3 whole screen is covered by gutter

![1](https://cloud.githubusercontent.com/assets/24775837/22691236/87add0f6-ed5f-11e6-90ec-071cfa416696.jpg)
![2](https://cloud.githubusercontent.com/assets/24775837/22691235/87aaa7dc-ed5f-11e6-98f1-e3c85282f352.jpg)
![3](https://cloud.githubusercontent.com/assets/24775837/22691237/87ae9ab8-ed5f-11e6-8625-ceb3088d3a66.jpg)
![4](https://cloud.githubusercontent.com/assets/24775837/22691238/87b245aa-ed5f-11e6-9968-2bbc0bdf9895.jpg)

**Comment by sardar-nale** [comment]
Hi,
Uploaded screenshots.
I have taken screenshots while scrolling down from top to bottom.
You can see in screenshot 3 whole screen is covered by gutter

![1](https://cloud.githubusercontent.com/assets/24775837/22691374/371c4054-ed60-11e6-8359-97eec4fc7bab.jpg)
![2](https://cloud.githubusercontent.com/assets/24775837/22691377/3720e8ca-ed60-11e6-853f-7e4c76467c5c.jpg)
![3](https://cloud.githubusercontent.com/assets/24775837/22691375/371cb976-ed60-11e6-9d6b-ab230b6bf3b1.jpg)
![4](https://cloud.githubusercontent.com/assets/24775837/22691376/371dd018-ed60-11e6-8476-3f6698f76ad8.jpg)

**Comment by bertrandg** [comment]
Thanks!
That's weird, I will investigate to solve it. 

Do you confirm you got same result on https://bertrandg.github.io/angular-split/#/examples ?
Which version are you using?

**Comment by sardar-nale** [comment]
I will check tomorrow about examples and let you know.
I am using angular-split@0.1.15 version

**Comment by bertrandg** [comment]
cool thx

**Comment by bertrandg** [comment]
That's ok, I managed to test it on safari (mac & ios) and yes... that's totally fucked!
It's a css problem, maybe missing prefix.. I let you know.

**Comment by bertrandg** [comment]
Ok I found, I need to remove a `height: 100px;` css rule on `<split-gutter>` that has no more utility.
I will make some tests and push it on NPM soon (before next week).

**Comment by sardar-nale** [comment]
I think it is     height: 100%; not 100px;
Is it okay to overwrite split-gutter to set it as null or something on my side.
like 
	split-gutter
	{  
	 height:none;
	}

**Comment by bertrandg** [comment]
yes that's a percentage, I will remove the rule.

**Comment by bertrandg** [comment]
I've just published a new version on NPM with fix (0.1.19).

But I've notice that flexbox wasn't available on ios (safari & chrome) before version 9:
http://caniuse.com/#feat=flexbox

So, if you have ios8 on your iphone6, that's "normal" it doesn't works and, sadly, it will never work on because this module use it in its core.

**Comment by bertrandg** [comment]
But the ios versions 9+10 percentage seems to be almost 95%:
https://developer.apple.com/support/app-store/

**Comment by sardar-nale** [comment]
Yes I wanted to share the same . So does there is any alternative for flexbox  ?

**Comment by bertrandg** [comment]
Not using angular-split, this lib is totally based on flexbox...
I will add it to the doc more clearly that it uses flexbox system.

You can use [split.js](https://nathancahill.github.io/Split.js/) which use "classic" float/width/height.
I coded a small angular (2+) handler for it but I don't maintain it anymore: [ng2-split](https://bertrandg.github.io/ng2-split/#/)

**Comment by sardar-nale** [comment]
No in Apple devices Safari browser by setting height also it doesn't work

**Comment by bertrandg** [comment]
height on what ?
using angular-split or split.js ?

**Comment by sardar-nale** [comment]
I have not tried split.js . but internally it uses i think calc function does it support to safari browser ?

**Comment by bertrandg** [comment]
http://caniuse.com/#feat=calc ("The Safari browser for iOS is tied to the operating system, so the numbers used are based on the OS version.")

Like for `flexbox``, ios 9 & 10 supports it but not sure about version 8.. 
Are you sure that your targeted audience is significantely under ios8 ?

**Comment by bertrandg** [comment]
And yes split.js use `calc` internally:
`width: calc(21.3466% - 5px);`
