### ISSUE TITLE
Compilation error while running package in prod after integration of angular -split 

### ISSUE THREAD

**Issue by bhagath007** [bertrandg/angular-split#50]
My package.json file:

{
  "name": "SampleApp",
  "version": "0.0.0",
  "description": "Description for SampleApp",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/animations": "4.2.6",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "4.2.6",
    "@angular/compiler": "4.2.6",
    "@angular/core": "4.2.6",
    "@angular/forms": "4.2.6",
    "@angular/http": "4.2.6",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "4.2.6",
    "@angular/platform-browser-dynamic": "4.2.6",
    "@angular/router": "4.2.6",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.28",
    "angular-split": "^0.2.2",
    "angular2-perfect-scrollbar": "^2.0.6",
    "bootstrap": "4.0.0-alpha.6",
    "chart.js": "^2.6.0",
    "core-js": "2.4.1",
    "css-ripple-effect": "^1.0.5",
    "font-awesome": "4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "3.2.1",
    "jquery-ui-bundle": "^1.12.1",
    "moment": "^2.18.1",
    "ng-jhipster": "0.2.7",
    "ng2-webstorage": "1.8.0",
    "ngx-cookie": "1.0.0",
    "ngx-infinite-scroll": "0.5.1",
    "primeng": "^4.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "swagger-ui": "2.2.10",
    "tether": "1.4.0",
    "uglify-js": "^3.0.28",
    "zone.js": "0.8.13"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "4.2.6",
    "@types/jasmine": "2.5.53",
    "@types/node": "8.0.13",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.2.1",
    "browser-sync": "2.18.12",
    "browser-sync-webpack-plugin": "1.2.0",
    "codelyzer": "3.1.2",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.28.4",
    "exports-loader": "0.6.4",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "0.11.2",
    "generator-jhipster": "4.6.2",
    "html-loader": "0.4.5",
    "html-webpack-plugin": "2.29.0",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.1",
    "karma-intl-shim": "1.0.3",
    "karma-jasmine": "1.1.0",
    "karma-junit-reporter": "1.2.0",
    "karma-notify-reporter": "1.0.1",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-remap-istanbul": "0.6.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.4",
    "merge-jsons-webpack-plugin": "1.0.8",
    "ngc-webpack": "3.0.0",
    "phantomjs-prebuilt": "2.1.14",
    "proxy-middleware": "0.15.0",
    "rimraf": "2.6.1",
    "sourcemap-istanbul-instrumenter-loader": "0.2.0",
    "string-replace-webpack-plugin": "0.1.3",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "tslint": "5.5.0",
    "tslint-loader": "3.5.3",
    "typescript": "2.4.1",
    "sass-loader": "6.0.6",
    "node-sass": "4.5.3",
    "postcss-loader": "2.0.6",
    "xml2js": "0.4.17",
    "webpack": "3.3.0",
    "webpack-dev-server": "2.5.1",
    "webpack-merge": "4.1.0",
    "webpack-notifier": "1.5.0",
    "webpack-visualizer-plugin": "0.1.11",
    "web-app-manifest-loader": "0.1.1",
    "write-file-webpack-plugin": "4.1.0"
  },
  "engines": {
    "node": ">=6.9.0"
  },
  "scripts": {
    "lint": "tslint --type-check --project './tsconfig.json' -e 'node_modules/**'",
    "lint:fix": "yarn run lint -- --fix",
    "ngc": "ngc -p tsconfig-aot.json",
    "cleanup": "rimraf target/{aot,www}",
    "clean-www": "rimraf target//www/app/{src,target/}",
    "start": "yarn run webpack:dev",
    "webpack:dev": "yarn run webpack-dev-server -- --config webpack/webpack.dev.js --progress --inline --hot --profile --port=9060",
    "webpack:build:main": "yarn run webpack -- --config webpack/webpack.dev.js --progress --profile",
    "webpack:build": "yarn run cleanup && yarn run webpack:build:main",
    "webpack:prod:main": "yarn run webpack -- --config webpack/webpack.prod.js --progress --profile",
    "webpack:prod": "yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www",
    "webpack:test": "yarn run test",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js",
    "test": "karma start src/test/javascript/karma.conf.js",
    "test:watch": "yarn test -- --watch",
    "postinstall": "node node_modules/phantomjs-prebuilt/install.js"
  }
}

Note: After implementation of angular-split I am unable to run package in prod. I am getting the below error. 

[ERROR] Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/SampleApp/node_modules/angular-split/node_modules/@angular/core/core.d.ts, resolving symbol AngularSplitModule in /home/SampleApp/node_modules/angular-split/dist/angularSplit.module.d.ts, resolving symbol AngularSplitModule in /home/SampleApp/node_modules/angular-split/dist/angularSplit.module.d.ts

Please help me out.

**Comment by zoroaster00** [comment]
I have the same problem with angular@4.2.6, is it compatible? Thanks.

**Comment by bhagath007** [comment]
Yes, It is compatible with angular@4.2.6. It is working in dev but failed while running the package in prod.
Thanks.

**Comment by zoroaster00** [comment]
It is known that it would fail while running in prod? Any possibility that it would get fixed? :)

**Comment by bertrandg** [comment]
I'm currently compiling in prod mode (with AOT) with CLI using:
`"@angular/cli": "1.3.0-rc.1"`
`"@angular/*": "4.3.2"`
`"angular-split": "0.2.2"`

And I'm almost sure I compiled it in prod with angular 4.2.x
That's weird if you have `angular-split 0.2.2`...

Anybody using custom webpack build instead angular-cli?

**Comment by bertrandg** [comment]
@zoroaster00 are you using CLI?

**Comment by bhagath007** [comment]
No, We are using webpack.Thanks!

**Comment by zanecat** [comment]
Hi I'm using cli and have met the same issue

after recomplie I met this:
Uncaught Error: Unexpected value 'AngularSplitModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by maxtacco** [comment]
Hi, we are having the same issue with Angular 4.4.0-RC.0 and Angular CLI 1.3.2

**Comment by maxtacco** [comment]
Downgrading to Angular 4.3.6 (still using CLI 1.3.2) and running:
```bash
npm uninstall angular-split
npm install angular-split -s
``` 
seemed to fix the issue for me.

Also, I've noticed that AngularSplitModule was imported twice in the module that contained my tree component - once through the "shared" module and once in the module itself. I updated my code to rely on the "shared' module import only. Not sure if that caused any issues though.

Also, still having an issue when using Angular 4.4.0-RC.0, but it is a different error.

Hope this helps.

**Comment by billdwhite** [comment]
Same issue here with 4.4.0-RC.0 and CLI 1.4.2

**Comment by bertrandg** [comment]
Ok I did some tests:
- cli `1.4.2` + split `0.2.2` + ng `4.4.0-RC.0` -> FAIL `ng serve` and `ng build --prod` with:

**ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported...**
- cli `1.4.2` + split `0.2.2` + ng `4.4.6` -> SUCCESS (`ng serve` & `ng build --prod`)
- cli `1.4.2` + split `0.2.2` + ng `4.3.6` -> SUCCESS (`ng serve` & `ng build --prod`)

- cli `1.5.0` + split `0.2.2` + ng `4.4.0-RC.0` -> FAIL
- cli `1.5.0` + split `0.2.2` + ng `4.4.6` -> SUCCESS (`ng serve` & `ng build --prod`)
- cli `1.5.0` + split `0.2.2` + ng `4.3.6` -> SUCCESS (`ng serve` & `ng build --prod`)

Version `4.4.0-RC.0` seems to be the problem there, so upgrade cli and/or angular.
And if it always fails, run:
`npm uninstall angular-split`
`npm uninstall angular-split@0.2.2`

**Comment by bertrandg** [comment]
Try latest 1.0.0 and reopen if still there.
