### ISSUE TITLE
Put the split component inside a flex-item which have a flex-grow to 1 

### ISSUE THREAD

**Issue by HugzM** [bertrandg/angular-split#51]
Hi, I'm trying to put the split component inside a div. this div is a flex-item with the following properties : 1 0 auto; the idea here is to have a vertical flexbox which contains a header , and the split component takes all the remaining available space in the flexbox under the header. 
Here is the plunker : [https://plnkr.co/edit/MbzZsXkPklp7tFc8foUF?p=preview](https://plnkr.co/edit/MbzZsXkPklp7tFc8foUF?p=preview
)

What I can do is include my header inside me split with a gutter size to 0 but i dont know in advance the height of my header to define the percentage of splitting

**Comment by bertrandg** [comment]
I don't really get your problems, I just added a css rule:
`body { margin: 0; }`

And it works, the header height in red isn't known in advance and the split component takes space left..
https://plnkr.co/edit/NPCGhM?p=preview

Is it what you want?

**Comment by HugzM** [comment]
I just try the plunker you sent and I can not drag the gutter to change the size of my splitted parts

**Comment by bertrandg** [comment]
Is it working as you want now?

**Comment by HugzM** [comment]
Oh yes sorry you were right It works fine ! thanks
