### ISSUE TITLE
(Re-)Size-sum != 100 if one split-area is not visible

### ISSUE THREAD

**Issue by Clemens-B** [bertrandg/angular-split#53]
If one split-area is not visible, the sum of the elements is not 100 after your resize one. Furthermore you can't really resize elements. 

https://plnkr.co/edit/upigdyZdAJ7QzI784JE4?p=preview

If you try to drag the last gutter to the right, it's not possible and the size of the last element keeps "33.33" even if you drag it to the left.

**Comment by Clemens-B** [comment]
Ok, it works correctly if you use *ngIf instead of [visible].

https://plnkr.co/edit/bsEwW5bkSlDAE8qFSX9h?p=preview

**Comment by bertrandg** [comment]
What you describe is normal, it's up to you to provide sizes of all **visible** areas equal to 100.
If not, it will be equal sizes to all visible areas.

And for the behavior with `[visible]="false"`, that's an ugly bug, I will check it!

**Comment by bertrandg** [comment]
I'm currently refactoring this library, I just published `1.0.0-beta.2` which solve the bug.

**Comment by bertrandg** [comment]
Just read again your issue about the sum, solves in `1.0.0`.
