### ISSUE TITLE
jit es5 build

### ISSUE THREAD

**Issue by jitsmaster** [bertrandg/angular-split#6]
I am trying to build angular-split as npm package and local deploy to test it. I tried both aot and jit build, both generate es6.  Do you have a custom build step to build es5? Also, is the NPM package aot build or jit build?

**Comment by bertrandg** [comment]
No es5 build..
Honestly, when I see how ng team promotes heavily TS (aot doesn't work without it) and how easy it is to setup a project using `angular-cli`, I really think es6 and TS are enought.

Currently `dist` folder contains AOT build.

**Comment by jitsmaster** [comment]
Sounds good.
