### ISSUE TITLE
Format split gutter

### ISSUE THREAD

**Issue by Skrutten** [bertrandg/angular-split#60]
Hi,

Im trying to format the splitgutter to own color and more, but with no success. :S
split-gutter {
    background-image: none !important;
    background-color: #123456 !important;
}

Any suggestions on how to make this possible?

BR

**Comment by bertrandg** [comment]
Sure, check this custom style example:
https://stackblitz.com/edit/angular-z4g7c9

**Comment by shirkedar** [comment]
Hi,
Can I define different background-image for vertical split-gutter and different background-image for horizontal split-gutter?

Thanks

**Comment by FatalTsai** [comment]
thx a lot
