### ISSUE TITLE
Feature request - Click event on splitgutter

### ISSUE THREAD

**Issue by Skrutten** [bertrandg/angular-split#61]
Hi, 

Would be awesome with an click event on the gutter.
e.g clicking on the gutter toggles from 50% to 20%. 
So instead of dragging one can toggle its pct.

**Comment by bertrandg** [comment]
hi @Skrutten,

I'm currently working on version 1.0.0 of the lib and just added a `gutterClick` event to toggle sizes or do whatever you want.

Here is a toggling example:
https://stackblitz.com/edit/angular-ppzkih

Warning: Always in beta (currently `1.0.0-beta.3`) and still several things to fix.

**Comment by Skrutten** [comment]
Nice, exactly what I was looking for. 
Great work

**Comment by bertrandg** [comment]
Cool, just updated the link to `beta.7`.
Now `[visibleTransition]="true"` becomes `[useTransition]="true"` (because it works for `[visible]` and `[size]`).

**Comment by chetanladdha** [comment]
https://stackblitz.com/edit/angular-ppzkih is not working in chrome ? Any workaround ?
