### ISSUE TITLE
Remove splitter between horizontal split areas and stack them one below other in mobile view

### ISSUE THREAD

**Issue by jainmitesh09** [bertrandg/angular-split#62]
Hello!

I have two horizontal split areas. When i reduce the screen size to mobile, I want to remove the splitter and have these areas one below the other. 

Any hint?

**Comment by bertrandg** [comment]
Nothing is builtin to do that with `angular-split` but you can do it yourself adding a listener on document resize and act accordingly.
If width down to x, just use 2 divs inside your template instead of `<split>...</split>`.
