### ISSUE TITLE
Getting Error TS2305 - 'no exported member' since version 2.4.  Imports in TS files do not work. 

### ISSUE THREAD

**Issue by billdwhite** [bertrandg/angular-split#64]
Ever since the change from 2.3 to 2.4 none of my imports in my TS files work.  I get this error for SplitAreaDirective, SplitComponent, etc:

ERROR in src/app/components/my-component.ts(3,9): error TS2305: Module '"/project/src/angulardemo/node_modules/angular-split/angular-split"' has no exported member 'SplitComponent'

Of course, this could be related to the change you made in starting in 2.4-2.6 but I'm not sure why simple imports would have stopped working....

**Comment by bertrandg** [comment]
Are you importing `SplitComponent` / `SplitAreaDirective` inside your components?
Normally you don't have to, just use it in your templates..
Show me your usecase.

**Comment by billdwhite** [comment]
Yes, that is exactly what I am doing.  My use case has a split pane that is initially closed and the user has a button that expands the pane from 0 with to an initial, visible width to reveal settings/controls.  Of course, the user could hover over the extreme edge of the screen to manually grab the splitter, but the "show controls" button is much easier to start with.  Therefore, if I want to do any type of programmatic manipulation, it is nice to be able to get a ViewChild handle to the components themselves.  As a workaround, I am able to use size variables bound to the template to change the size so I have a work around (this is probably the preferred approach anyway).   However but it is still convenient to be able to interact with the component using typescript which requires the ability to import it.

**Comment by bertrandg** [comment]
hum.. the library wasn't built to be used like that (in fact I never think about it). 
And in last version I effectively removed components/directives from public definition.

Here is a way to do what you want, tell me if it solves what you need:
https://stackblitz.com/edit/angular-t2t3xs

In case not, please code me a stackblitz using angular-split 0.2.3 and showing what you do currently.

**Comment by billdwhite** [comment]
I previously used another split pane implementation that did not support transitions so I was accessing the components programmatically and tweening the position of the splitter to animate the open/close.  You are correct that I can achieve this same effect without having to access the components in code since you have the 'visibletransition' property. (which does not work in Safari by   the way but that is another issue)  Therefore, I am able to continue using this component as designed after changing how I get/set those properties.

**Comment by bertrandg** [comment]
Just to let you know, I think again to your usecase and you're right, access `SplitComponent` and `SplitAreaDirective` from the js/ts should be possible.

I'm currently refactoring this library, I just published 1.0.0-beta.2 which give access again.
https://github.com/bertrandg/angular-split/blob/master/CHANGELOG.md

**Comment by billdwhite** [comment]
@bertrandg That's great.  While I was able to work around without having direct access to those classes, it is certainly more flexible to provide access to those classes for directly interaction within typescript/javascript.  Thanks!
