### ISSUE TITLE
100% height issue

### ISSUE THREAD

**Issue by matte00** [bertrandg/angular-split#65]
I'm using your library in a Flex project and platform.css (now layout-flex) but it's don't works. 
I must remove hight :100% from splitArea e splitGutter. Without these, now it's working

```
<div style="position: absolute;top:50px;bottom:0;right:0;left:0">
  <div layout="row" layout-fill>
    <div layout="column" layout-fill>
      <split [direction]="'horizontal'" [gutterSize]="8">
        <split-area [size]="25" [order]="1">
          <p>Test</p>
        </split-area>
        <split-area [size]="75" [order]="2">
          <split [direction]="'vertical'" [gutterSize]="8">
            <split-area [size]="50" [order]="1">
              <p>Top Content</p>
            </split-area>
            <split-area [size]="50" [order]="2">
              <p>Bottom Content</p>
              <p>Bottom Content</p>
              <p>Bottom Content</p>
              <p>Bottom Content</p>
              <p>Bottom Content</p>
              <p>Bottom Content</p>

              <p>Bottom Content</p>
              <p>Bottom Content</p>
            </split-area>
          </split>
        </split-area>
      </split>
    </div>
  </div>
</div>

```

**Comment by bertrandg** [comment]
Are you talking about `@angular/flex-layout`?

If yes, checkout this demo:
https://stackblitz.com/edit/angular-w55rly?file=app%2Fapp.component.html

If it doesn't help, please provide a stackblitz.

**Comment by digitalcoyote** [comment]
https://stackblitz.com/edit/angular-y1rpku I am not using @angular/flex-layout and seeing that in chrome's inspector disabling the height: 100%: or setting it to a negative number allows it to work as in the demo.

**Comment by WillooWisp** [comment]
I experience the same thing, removing height: 100% from split-area and split-gutter is necessary in order for gutter to get any height at all (it gets the correct height as well).

**Comment by lroitman** [comment]
Same here. We don't use flex-layout, and the gutter is not shown unless I remove height: 100% from split-gutter in Chrome inspector. Any suggestion of a workaround?

**Comment by jopuckman** [comment]
As a workaround, you can set the gutter height to its initial height.

`split-gutter {
    height: initial !important;
}`

**Comment by dpatel44725** [comment]
What is the status on this issue ? Can we support height in % instead of px ?

**Comment by digitalcoyote** [comment]
I had a code pen to show this issue, but when I last checked it, it appeared to be working with the latest version. https://codepen.io/digitalcoyote/pen/WdQzQV

**Comment by dpatel44725** [comment]
I have created demo here please check, when giving 
```
height : 100%
```

it doesn't work properly.

https://stackblitz.com/edit/angular-m6czv2

if you could resolve this that would be great help.

**Comment by digitalcoyote** [comment]
The original codepen I had poosted was wrong: https://stackblitz.com/edit/angular-9v5fzk shows this as working in Chrome. It does need an explicit height set on body/html though b/c that is where it is deriving it's height from.

**Comment by dpatel44725** [comment]
Thank you @digitalcoyote  :) for response, I got the idea. 

In complex , applications the parent component needs to have height set explicitly. then if we give height in % that works fine. 

Thanks you again @digitalcoyote. 

And thank you @bertrandg  for this awesome plugin. and updating it  when i needed it mostly.

**Comment by smartm0use** [comment]
> As a workaround, you can set the gutter height to its initial height in your application's css.
> 
> `split-gutter { height: initial !important; }`
> 
> EDIT: For version 1.0.3 (at least), you can use the following instead:
> 
> `as-split-gutter { height: initial !important; }`

It is not working in my case: https://stackblitz.com/edit/angular-rcqyv1
What's wrong?

**Comment by smartm0use** [comment]
> The original codepen I had posted was wrong: https://stackblitz.com/edit/angular-9v5fzk shows this as working in Chrome. It does need an explicit height set on body/html though b/c that is where it is deriving it's height from.

What about if I'm in a modal and the parent container is scrollable (with `max-height: calc(80vh - 10rem)`)?
