### ISSUE TITLE
Patch Release Backward Compatibility

### ISSUE THREAD

**Issue by jamesqquick** [bertrandg/angular-split#66]
I have been using version 0.2.2 of angular-split with version 4.2.4 of Angular, and everything worked fine.  In my package.json, i defined the dependency on angular-split with the '^' symbol, meaning I should be able to take patches and minor updates without (in theory) causing issues.

However, when doing a fresh npm install, I got the latest patch version of angular-split, which is 0.2.6.  Apparently, this patch version has a dependency on Angular 5.0.0 which caused my application to fail to build. 

After about an hour of trying to figure this out, I did figure out the problem.  I wanted to raise the issue though, because I would not expect to get breaking changes with a patch.  In my mind, if angular-split needs to change its dependency on Angular to  a newer version, this should be a major change.  I would highly suggest testing backwards compatibility before pushing patch released.

**Comment by bertrandg** [comment]
Yes, I screwed up about semver there, sorry for the wasted time. I talked about it there:
https://github.com/bertrandg/angular-split/issues/63
I will do better next time!

I already had this kind of painful debugging time and always block all dependencies version now..

**Comment by bertrandg** [comment]
Just published `0.2.7` which is a copy of `0.2.3` (so compatible with angular 4). ;)

**Comment by jamesqquick** [comment]
All sounds great. Thanks so much for the quick response and feedback. Other than that, the package has worked great! :)
