### ISSUE TITLE
visibleTransition

### ISSUE THREAD

**Issue by hardav31** [bertrandg/angular-split#67]
[visibleTransition]="true"  transition doesn't work....(I know that I have to use visibleTransitionEnd ,but in preveious version it  worked perfactly without visibleTransitionEnd  )  and  I have this warning ` /deep/ combinator in CSS is deprecated and will be removed in M63, around December 2017........

**Comment by bertrandg** [comment]
I need more info (cli or not, cli version, angular version, angular-split previous and current version, browser,...) and a demo (stackblitz/plunker) to help you....

I don't understand what you mean, `(visibleTransitionEnd)` event isn't necessary to have `[visibleTransition]="true"`, that's use to know when transition ends..
And about `/deep/` css warning, I know, I'm currently refactoring the lib (`1.0.0-beta.4`) and get rid off it.

**Comment by hardav31** [comment]
"@angular/cli": "1.4.5"   "angular-split": "0.2.2"  and "0.2.7" --doesn't work transition
"@angular/cli": "^1.0.3", "angular-split": "0.2.2" --work normal...

in "angular-split": "0.2.2" version I only had to add [visibleTransition]="true" and transition would work....
about /deep/ what Do I have to do???

**Comment by bertrandg** [comment]
Try latest 1.0.0 and reopen if still there.
