### ISSUE TITLE
Angular 5.0 and Angular-Split 0.2.7

### ISSUE THREAD

**Issue by RafaeldelM** [bertrandg/angular-split#68]
Hi,

First of all, thanks for your work on Angular-Split. :-)

I'm trying to install in Angular 5.0, but it 0.2.7 is not working. I think 0.2.7 is for 4.0, but the code is updated to 5.0. Is there a way I can use it before you release the new code by NPM?

Thanks,

Rafa

**Comment by zanecat** [comment]
try 1.0.0-beta.5 with ng5

**Comment by bertrandg** [comment]
angular-split `0.2.7` should works with angular `5.0.0`, here is a demo showing it:
https://stackblitz.com/edit/angular-lkn9uz?file=app%2Fhello.component.ts

Test to uninstall an reinstall it:
`npm uninstall angular-split`
`npm install angular-split@0.2.7`

**Comment by bertrandg** [comment]
But like @zanecat said, you can use `1.0.0-beta.6` with angular `5.0.0` minimum.
