### ISSUE TITLE
Order changes when toggle visible

### ISSUE THREAD

**Issue by zanecat** [bertrandg/angular-split#69]
Hi bertrandg,
I have two <split-area> with order 0 and 1, and I the 0 is toggle-able with a button. When I set 0 invisible and back, the order of them changed to 2 and 1. Is this my issue or a bug?

This happened after I update from 0.2.2 to 1.0.0-beta.5.

Thanks!

**Comment by bertrandg** [comment]
I tried what you say (with `1.0.0-beta.5`) and it works, order is keeped:
https://stackblitz.com/edit/angular-k2op76?file=app%2Fhello.component.ts

**Comment by bertrandg** [comment]
Oh I just got what you mean, you are not using `[order]`!
Yes that's normal to react like this, now you have to set a `[order]` property if you want to keep order while toggling `<split-area>` presence using `*ngIf` of `[visible]` (Before `1.0.0` using `[visible]` keep order by default).

**Comment by zanecat** [comment]
Alright, thanks very much. This is a fantastic ng plugin  btw.
