### ISSUE TITLE
Unable to see split gutter

### ISSUE THREAD

**Issue by mastiffXing** [bertrandg/angular-split#7]
Using the horizontal split I don't see the gutter. If I use the vertical split I see the gutter but can't move it. 

The only way I can get it to show up and work is by changing the height in the generated element style for the split tag from 100% to 300px. (I found this using firebug.)  I've tried adding height to the parent but it made no difference.

In the other split issue an you suggested: 
_Set it to specific height in pixels: height: 300px, what I did here: https://bertrandg.github.io/angular-split/#/examples_ . I couldn't find height this in the example.

I'm using angular-cli 1.0.0-beta.25.5.

**Comment by bertrandg** [comment]
hi @mastiffXing,

Seems to be related to your height container set in percentage.
Read this to understand better how percentage height works in css: http://stackoverflow.com/questions/5657964/css-why-doesn-t-percentage-height-work

checkout this issue if you still have the problem: https://github.com/bertrandg/angular-split/issues/2
