### ISSUE TITLE
ERROR in Error: Unexpected value 'AngularSplitModule

### ISSUE THREAD

**Issue by martinknafve** [bertrandg/angular-split#71]
We are getting the following error when using angular-split 0.2.7.

> ERROR in Error: Unexpected value 'AngularSplitModule in <path>/node_modules/angular-split/dist/angularSplit.module.d.ts' imported by the module 'SharedModule in <path>/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.

If we revert to angular-split 0.2.6 everything works as it should. So our workaround is currently to use the older version, but of course we want to understand why it fails with the latest. I suspect this is the same issue as #70 and that the error message differs just due to us using a different angular version.

We just use a normal import to import it:
`import { AngularSplitModule } from 'angular-split';`

ng --version gives me the following output:

```Angular CLI: 1.5.0
Node: 6.10.1
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.5.0
@angular/tsc-wrapped: 0.4.2
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1```

**Comment by bertrandg** [comment]
Please checkout the answer I just did on https://github.com/bertrandg/angular-split/issues/70.

Anyway, if you are using angular `5.x`, use latest `1.0.0-beta-9`.
Even if it's tagged beta, it's more robust than `0.2.x`, you can have a look on preview [doc](https://bertrandg.github.io/angular-split/beta/#/documentation) & [demo](https://bertrandg.github.io/angular-split/beta/#/examples/geek-demo)

**Comment by martinknafve** [comment]
Thanks! We've set our dependency to ~1.0.0-beta.9 || ^1.0 and now it works fine.
