### ISSUE TITLE
Building application in production mode is imposible

### ISSUE THREAD

**Issue by naduda** [bertrandg/angular-split#72]
### Reproduction steps:
1. ng build test-angular-build
2. cd test-angular-build
3. npm install angular-split (or npm install angular-split@1.0.0-beta-9)
4. add AngularSplitModule to app
5. ng build --prod

ERROR in Error: Unexpected value 'AngularSplitModule in .../test-angular-split/node_modules/angular-split/dist/angularSplit.module.d.ts' imported by the module 'AppModule in .../test-angular-split/src/app/app.module.ts'. Please add a @NgModule annotation.

What can I do in this situation?

### ng --version
Angular CLI: 1.5.4
Node: 6.11.2
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.5.4
angular-devkit/build-optimizer: 0.0.33
angular-devkit/core: 0.0.21
angular-devkit/schematics: 0.0.37
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.4
schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

**Comment by bertrandg** [comment]
Just tried your scenario with  `angular-split@1.0.0-beta.9`:

Angular CLI: 1.5.4
Node: 8.9.0
OS: win32 x64
Angular: 5.0.3
   animations, common, compiler, compiler-cli, core, forms
   http, language-service, platform-browser
   platform-browser-dynamic, router

angular/cli: 1.5.4
angular-devkit/build-optimizer: 0.0.33
angular-devkit/core: 0.0.21
angular-devkit/schematics: 0.0.37
ngtools/json-schema: 1.1.0
schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1


Works good compiling with `ng serve`, `ng build --prod` and works good running these 2 versions in browser...

**Comment by ivarmah** [comment]
Hey.
Same error for us, when building with `ng build --target=production`.
Angular CLI: 1.5.4.
Node: v7.0.0.
OS: OSX high sierra
Angular: 4.4.6.
It works fine in dev mode :) with `ng serve`.


```
ERROR in Unexpected value 'AngularSplitModule in /Users/user/Desktop/Projects/company/project-name/node_modules/angular-split/dist/angularSplit.module.d.ts' imported by the module 'ProductsModule in /Users/user/Desktop/Projects/company/project-name/src/app/products-management/products.module.ts'. Please add a @NgModule annotation.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/user/Desktop/Projects/company/project-name/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/user/Desktop/Projects/company/project-name/src'
  using description file: /Users/user/Desktop/Projects/company/project-name/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/user/Desktop/Projects/company/project-name/package.json (relative path: ./src)
    using description file: /Users/user/Desktop/Projects/company/project-name/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory]
[/Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/user/Desktop/Projects/company/project-name/src/$$_gendir/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

**Comment by naduda** [comment]
Realy. It works. Thanks.

**Comment by ivarmah** [comment]
We updated our project to Angular 5, but still can't use it in prod mode with `ng build --prod`. :)

Angular CLI: 1.5.4
Node: 7.0.0
OS: darwin x64
Angular: 5.0.3

```
ERROR in Error: Unexpected value 'AngularSplitModule in /Users/user/Desktop/Projects/company/project/node_modules/angular-split/dist/angularSplit.module.d.ts' imported by the module 'MyComponentModule’ in /Users/user/Desktop/Projects/company/project/src/app/my-component/my-component.module.ts'. Please add a @NgModule annotation.
```

**Comment by askalia** [comment]
I did the following and it works  👍 
import {AngularSplitModule} from "angular-split**/dist**";

**Comment by ivarmah** [comment]
We fixed the issue somehow by using:
 "angular-split": "1.0.0-rc.0"
Previously we were using:
 "angular-split": "0.2.7" :) 👍
