### ISSUE TITLE
Scroll Bar 

### ISSUE THREAD

**Issue by n614cd** [bertrandg/angular-split#73]
Short: ability to override the scroll bar behaviour in a split area.

Preferable solution; add an input param for the css classname. If provided, assume we know what we are doing and will set the values appropriately and not provide any built in styling.

Longer: background I have dynamic sizing of a series of material cards in a split area. Based on a bunch of factors I adjust the size of the card, and what information is displayed. So, when the browser determines a scroll bar is needed, if you size the window just so, the scroll bar flashes on/off and it adds the scroll bar, resizes the elements just one pixel smaller which eliminates the need for the scroll bar, which expands the display width causes a recall of the expected width, which causes the additional line to display which adds the scroll bar back....

**Comment by bertrandg** [comment]
Thanks to report it, yes it could be usefull,
can you provide a stackblitz of your scenario?

**Comment by n614cd** [comment]
This is as close as I could get it: https://angular-trkxh6.stackblitz.io

**Comment by bertrandg** [comment]
Hi @n614cd 
If you are still interested in this feature (I know it's been long time!), check this stackblitz:
https://stackblitz.com/edit/angular-andtvw?file=src%2Fapp%2Fapp.component.html

The 2.x is still beta, I need to test it on major browsers before release.

**Comment by bertrandg** [comment]
Possible with version `2.0.0` I've just released.
