### ISSUE TITLE
First initial to split area not render

### ISSUE THREAD

**Issue by yasin-mansour** [bertrandg/angular-split#78]
https://github.com/bertrandg/angular-split/blob/f2a55b540b9b8f672bccad0159d9b913d11a3eb9/src/components/splitArea.directive.ts#L83

You add the split area to the split component in the ngOnInit callback and set to update the split in any change on the size, order, minsize or visibility change, that work fine, but since the setter function call before ngOnInit callback in the first load, this would cause an issue in rendering the First initial value for all parameters. 

It's like asking to update the view for area not added to the split, I think you need to call the update function in the ngOnInit callback to solve this issue

**Comment by bertrandg** [comment]
You're right for the function calls order at first time.
But inside `SplitComponent`, the `addArea()` function calls `build()` function anyway like the `updateArea()` would have done it.
And `build()` function use latest `SplitAreaDirective` properties values so it works as expected for me.

Why did you say this, have you experiment bug at initialisation?
If yes, feel free to reopen this issue with a stackblitz demo.
