### ISSUE TITLE
feature: ability to specify new defaults

### ISSUE THREAD

**Issue by thefliik** [bertrandg/angular-split#79]
This package is awesome! Thanks so much for publishing it!

A "nice to have" addition would be the ability for an app to overwrite the built-in defaults. Perhaps by implementing `AngularSplitModule.forRoot()` and `AngularSplitModule.forChild()` (or `AngularSplitModule.forFeature()`) and passing an options object during the module import

```
@NgModule({
  imports: [
    AngularSplitModule.forRoot({
      component: {
        direction: '',
        width: '',
        height: '',
        gutterSize: '',
        gutterColor: '',
        gutterImageH: '',
        gutterImageV: '',
        disabled: '',
        useTransition: '',
      },
      directive: {
        size: '',
        visible: '',
      }
    })
  ]
})
```

**Comment by thefliik** [comment]
I should also add: in several places you inline the styles directly on an element. The result is

1. The dev needs to make use of the element's input property to alter those styles.
2. A global option would be nice.

For example, the only (good) way of setting a gutter's color is via the `[gutterColor]` input, because the color value is inlined on the gutter (preventing me from styling it with CSS). If the color value were applied as overwritable css, then I could use css to color the gutter and wouldn't need a global config option.

Making use of css selectors, where possible, would probably be superior to a global config option. Though obviously some of the configs would remain as input options (e.g. `size`).

**Comment by bertrandg** [comment]
You're totally right, the way to set color/imageH/imageV is not good, that's CSS cascading job to manage that.
Thanks, I'm gonna change that.

**Comment by bertrandg** [comment]
Hi @thefliik 
If you are still interested in this feature (I know it's been long time!), check this stackblitz:
https://stackblitz.com/edit/angular-andtvw?file=src%2Fapp%2Fapp.component.html

The 2.x is still beta, I need to test it on major browsers before release.

**Comment by thefliik** [comment]
@bertrandg awesome! If you're asking how the stackblitz example renders on my browser, it looks great (Chrome 66 on OSX 10.11.6).

At the moment, I think I may be overwriting angular-split's styles using `!important`
