### ISSUE TITLE
Run event listeners outside ngZone

### ISSUE THREAD

**Issue by klemenoslaj** [bertrandg/angular-split#80]
First of all, great work, thanks for that. I have some questions:

Is it by design that all the event listeners are running inside ngZone?
Isn't this a big overhead for a large applications?
Would it be possible to run outside ngZone?

**Comment by bertrandg** [comment]
hi,
That's not by design and you're right, add 
`this.zone.runOutsideAngular(() => { /* set event listeners */ });` should improve performance!

I will first make some tests and add it, 
thanks to you! :)

**Comment by klemenoslaj** [comment]
Great, thanks a lot for your efforts :)

**Comment by bertrandg** [comment]
Done in rc1 ;)
https://bertrandg.github.io/angular-split/#/changelog
