### ISSUE TITLE
Restrict gitter move part of screen

### ISSUE THREAD

**Issue by Thinkerguider** [bertrandg/angular-split#82]
Thanks for your good plugin. And allowing me to log an enhancement.

How to restrict gitter to move from 50-70% of screen? means, I have a button in first panel, if I click on that button I am showing right panel. I wanna restrict right panel min width 30% and max width 50%. Gitter also should support me to move only from 30% to 50% of screen.

**Comment by bertrandg** [comment]
Check #131 for what's coming.
