### ISSUE TITLE
Doesn't work in a mat-sidenav-container

### ISSUE THREAD

**Issue by andrewinkler1** [bertrandg/angular-split#86]
The split pane doesn't work in a mat-sidenav-container. The first split area is not recognized:

split area 1 css:
 order: 0
 flex: 0 0 calc(0% - 0px)

split area 2 css:
 order: 2
 flex: 0 0 calc(100% - 11px)

**Comment by thefliik** [comment]
I've been using AngularSplit in a mat-sidenav-container without issue.
