### ISSUE TITLE
Order is not given when split-area is temporarly removed.

### ISSUE THREAD

**Issue by MTschannett** [bertrandg/angular-split#89]
When a split area gets removed over the [visible] property binding, the order gets a wrong value.

I think the order gets incremented. 

My problem with this is, that when i make a column (which is on the left side at first) i wan't to have it on the left side when it gets visible again.

I tracked it down to a css order parameter which gets a new value.

**Comment by MTschannett** [comment]
I just saw that there is a input property given for the split area, which solves my problem. 

Documentation is here: https://bertrandg.github.io/angular-split/#/documentation

**Comment by celestale** [comment]
I tried [visible] too and the order gets incremented too.

I hide the column on the left with [visible] but when it gets visible again, it gets pinned on the right side.

How did you fix it?

**Comment by bertrandg** [comment]
Use `order` property to keep order whatever `visible` properties changes:
```
<as-split>
   <as-split-area order="1" [visible]="isVisibleA">A<as-split-area>
   <as-split-area order="2" [visible]="isVisibleB">B<as-split-area>
</as-split>
```
