### ISSUE TITLE
Hide panel without destroy 

### ISSUE THREAD

**Issue by karmis** [bertrandg/angular-split#9]
If I want hide panel - I must destroy all components of my panel
```html
<split-area *ngIf="isVisible">
<my-module></my-module>
</split-area>
```
How I may just hide panel without destroying my components ?

```css display: none ```  and ```(size)=0``` not working for me because module does not recalculating count of split-area's

Need like that 
<split-area [hidden]="isHidden"></split-area>

**Comment by bertrandg** [comment]
Actually, only `ngIf` works to remove/hide an area.

But you will could do that soon when this pull-request will be merged: https://github.com/bertrandg/angular-split/pull/8
You will have to do like this: `<split-area [visible]="false"></split-area>`

**Comment by karmis** [comment]
Ok, thanks ... 
Now as temporary solution Im do it:

```javascript
            self.splitOne.nativeElement.style.flex = '0 0 calc(' + splitOne + '%)'; // splitOne = 0
            self.splitTwo.nativeElement.style.flex = '0 0 calc(' + splitTwo + '%)';
```

**Comment by bertrandg** [comment]
Good news for you :)

Pull request has been merged, you can know toggle area visibility without removing it from the DOM using `<split-area [visible]="false"></split-area>`.

Install 0.1.17 to get it!
Keep me informed if it works as you expect and close this issue if it's ok.

**Comment by karmis** [comment]
Ok!.Thanks

**Comment by karmis** [comment]
Great work. Thanks for your module. All working.
