### ISSUE TITLE
Expose current areas sizes?

### ISSUE THREAD

**Issue by lroitman** [bertrandg/angular-split#91]
It would be nice to have some access to current area sizes. The use case I am trying to work on is the user drags the gutter to the desired position, then hides one area, and then wants to restore the area to the position it was when it was hidden.
It looks like all the info is in the split component, but it is not exposed. 
Do you think something like that is worth implementing?

**Comment by bertrandg** [comment]
Hi, you can already do it using `dragEnd` event and memorize it to use it again later.
