### ISSUE TITLE
Size is refusing to go to 0 (zero).

### ISSUE THREAD

**Issue by TomashVlad** [bertrandg/angular-split#92]
I use Angular 2 and 0.2.7 version of angular-split. It is working fine, but one problem is happening. When I try to pull bars all the way to end of field, it will stop around 100px from side end. This is happening in both directions. When I try plunker, it is working just fine and I can drag them all the way to the end practically hiding one div, but for some reason, that is not the case in my project. Has any of you had any similar situation, or do you have any suggestion for solving this problem?

You can see that in this picture: [https://i.imgur.com/xP6DRRF.png](url)
(copy link in browser if for some reason it won't open on click)

Update: 
Just discovered that this problem is happening for all sections. If I have div split in 3 sections, for all of them is looking like they have defined min-width and when i pull bar to end it will stop on these data (see how flex hits 5% and that is limit it is refusing to pass, but it should let me to go to 0).

`<split-area _ngcontent-c1="" style="order: 2; flex: 0 0 calc(5% - 6.66667px); overflow-x: hidden; overflow-y: auto; height: 100%;"><div _ngcontent-c1="" style="position:relative; float: left; height: 100%; width: 100%;">`

I founded that in split.component.js there is defined "this.minPercent = 5;" and when I change that to 0, I am able to drag bar as it should be ...my question is ...how can I fix this, cause in that case npm package will set that value to 5 every time i install application on another pc? @bertrandg  Can you make it 0 by default for 0.2.x versions?

**Comment by matthieucolas** [comment]
Same issue here ...

**Comment by bertrandg** [comment]
Related to an old angular-split version (0.2.x) not maintained anymore...
Try latest 1.0.0 and reopen with stackblitz demo if still there.
