### ISSUE TITLE
Potential for a pane to just wrap content by default

### ISSUE THREAD

**Issue by ronnyek** [bertrandg/angular-split#93]
I've got a vertical set of panes, and left pane (nav) is typically populated with dynamic content. I was wondering if there was a way to just have that left pane be defaulting to size that wraps the left nav's width, and then if user wants to resize, more power to them.

I dont understand enough about how splitter is working under the scenes to know or try to help out there.

**Comment by bertrandg** [comment]
hi, sorry but it would a nightmare to code something like that, too much cases! 😜
And that's out of the library scope.
