### ISSUE TITLE
npm ERR! 404 401 Unauthorized: angular-split@latest

### ISSUE THREAD

**Issue by srjkrl20011991** [bertrandg/angular-split#96]
I am trying to install in angular 4 project ...
**npm install angular-split**
----------------------------------------------
npm ERR! code E401
npm ERR! 404 401 Unauthorized: angular-split@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\suraj.karale\AppData\Roaming\npm-cache\_logs\2018-03-20T05_12_32_864Z-debug.log
----------------------------------------------------

Why this error is thrown by npm?

**Comment by bertrandg** [comment]
Seems not related to angular-split...
Try latest 1.0.0 and reopen if still there.
